### ISSUE TITLE
Stoffliches müsste gesäubert werden

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#101]
![2014-05-12 13 37 11](https://cloud.githubusercontent.com/assets/3153638/2944021/59bd6fec-d9cd-11e3-9b70-56463e1173b1.jpg)
![2014-05-12 13 37 33](https://cloud.githubusercontent.com/assets/3153638/2944020/59bd640c-d9cd-11e3-826c-17e63b609644.jpg)

Die Kissen & Couch sind teils recht dreckig, da muss man mit geegneiten Säuberungsmaterial rangehen. Kennt sich da jemand aus?

**Comment by moba** [comment]
Ich würde das als immer noch aktuell bezeichnen, inzwischen sind noch eine Couch, Sessel, und Teppiche hinzugekommen.

**Comment by grindhold** [comment]
die couch ist inzwischen ersetzt, wurde nach draussen versetzt und verwittert vor sich hin. Die issue ist nicht mehr relevant.
