### ISSUE TITLE
Flipdots sinnvoll einsetzen

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#105]
Jetzt haben wir zwar so ein tolles Flipdot-Nubsi, aber was machen wir damit?

Ideen müssen her!

**Comment by grindhold** [comment]
da #108 fertig ist, vorschlag zur guete:

EFA-abfahrtsanzeige fuer unsere haltestelle
wenn labping kommt, den content des pings anzeigen

**Comment by lukasepple** [comment]
Man müsste sich mal ein sinnvolles Schema überlegen, wie man diese dauerhaft laufenden services unterbricht, um z. B. flippybird oder flong zu spielen

**Comment by lukasepple** [comment]
Viel besser: [doge](http://www.nikriek.de/images/posts/retrospective-31c3/doge.jpeg)

**Comment by sternenseemann** [comment]
Gibt jetzt [flipdot-gschichtler](https://github.com/openlab-aux/flipdot-gschichtler), werde die Tage nochmal testen, ob der noch geht, iirc ist der service kaputt gegangen.
