### ISSUE TITLE
Flipdots reparieren

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#108]
Sind kaputtgegangen.

16:40:23      Profpatsch | phil____: Sind die Pixel an sich kaputt oder die Steurung?
16:41:01        phil____ | sowohl als auch. mindestens ein pixel ist komplett tot und einige zeilen/spaltentreiber hats erwischt
16:41:18        phil____ | ohne ein ersatzpanel ist die reperatur quasi nicht möglich
16:45:53       michiwend | sternenseemann: nope, ich bin erst montag wieder im lab
16:47:13       michiwend | sternenseemann: zu den flipdots selber: krobin wollte mal wegen nem ersatzpanel gucken... weiß nicht, wie der stand da ist

**Comment by grindhold** [comment]
wurde gestern von @michiwend erledigt.
kudos, michi :)

**Comment by lukasepple** [comment]
all the blumenkraft belong to @michiwend
