### ISSUE TITLE
Wikiseiten „Verfallsdaten“ zuordnen können.

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#114]
Man sollte ein Datum festlegen können, bei dem Erinnerungen rausgehauen werden, dass Wikiseite x mal wieder überarbeitet werden soll.

Ich könnte mir ein taskwarrior-Backend dafür vorstellen, das tut diese Dinge mit Scheduling ganz gut.

Würde enorm helfen, die Wiki aktuell zu halten.

**Comment by sternenseemann** [comment]
Für's nächste Wiki neu lösen.
