### ISSUE TITLE
Sphinkter auf Wiki dokumentieren

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#117]
Das Projekt braucht eine Doku, damit andere auch profitieren können und es eventuell nachbauen können.

Vllt. sollte https://github.com/openlab-aux/orgafoo/issues/116 davor erledigt werden und sich dann danach gerichtet werden.

**Comment by verbosemode** [comment]
IMHO ist die aktuelle Doku super. https://wiki.openlab-augsburg.de/openwiki:projekte:schliessanlage

Issue schließen?

**Comment by grindhold** [comment]
jo. so schaut doku aus :)
