### ISSUE TITLE
logpolicy für `labctl` festlegen

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#126]
Sollen logs aufgezeichnet werden? Wenn ja, wie oft werden sie gelöscht?

@waaaaargh @moba

**Comment by sternenseemann** [comment]
ping

**Comment by sternenseemann** [comment]
Noch aktuell?

**Comment by Profpatsch** [comment]
Jau, momentan ist das Log afaik ewig, sollte man zwecks Datenschutzgründen drüber reden (durch sphincter-Webserverdaten können Rückschlüsse gezogen werden, wer wann aufgesperrt hat).

**Comment by sternenseemann** [comment]
Journald `SystemMaxUse=1M`?

**Comment by Profpatsch** [comment]
Sowas, ja.

**Comment by Profpatsch** [comment]
Eher über Zeit. Ich denke ein Monat Daten vorhalten wäre sinnvoll.

**Comment by sternenseemann** [comment]
Okay, dann sollte in die `journald.conf`:

```
MaxFileSec=1month
SystemMaxUse=1G # oder was auch immer 
```

**Comment by sternenseemann** [comment]
Nee, falsch:

```
MaxRetentionSec=1month
SystemMaxUse=1G # oder was auch immer 
```

**Comment by robinkaranu** [comment]
sphincter wird in wenigen Tagen aus gehen. wontfix
