### ISSUE TITLE
OpenLab Packstation

### ISSUE THREAD

**Issue by Velocet** [openlab-aux/orgafoo#137]
Wie steht das Lab dazu, einen Account bei der Post zu erstellen damit Pakete an eine Packstation geliefert werden können?

**Comment by moba** [comment]
Hmm. Schließen?

**Comment by Profpatsch** [comment]
Will sich da noch jemand drum kümmern? Wie ist der Status? Nutzt das Jemand?

**Comment by sternenseemann** [comment]
Funktioniert das prinzipiell? Oder muss man da TANs empfangen?

Wenn das geht würde ich es dokumentieren.

@Velocet

**Comment by Velocet** [comment]
Die Packstation funktioniert. Genauso wie der Amazon Ref-Link. Jemand müsste mal ne SIM-Karte kaufen (anonym und so..) und die der Packstation zuordnen. Mails kommen immer noch bei mir an. Würde das gerne auf einen Account vom Lab laufen lassen. Tickert mich über Twitter an...

**Comment by sternenseemann** [comment]
Idee: Mailaccount auf dem WandTablet anlegen. Allerdings siehe #231.

Wofür braucht man genau eine Handynummer? Ein normales Telefon haben wir
ja im Labor.

**Comment by Velocet** [comment]
Weil dorthin die TAN/PIN für das Paket geschickt wird wenn es in der Packstation eintrifft. Man kriegt zwar auch per Mail bescheid, jedoch die TAN/PIN nur per SMS.

**Comment by sternenseemann** [comment]
Oh, okay. Das WandTablet hat vmtl. keinen SIM-Slot @phjlipp?

**Comment by sternenseemann** [comment]
Für einen Mailaccount hätten wir jetzt das WandTablet.

**Comment by phjlipp** [comment]
Von einem SIM-Slot wieß ich nichts, das Tablet hat keinen.

**Comment by sternenseemann** [comment]
Also:

Benötigt:

* E-Mail-Account, der auf dem WandTablet eingerichtet wird
* $Handy für TAN-Empfang

**Comment by Velocet** [comment]
$Handy liegen noch welche im Lab rum.
Wahlweise mal im IRC nach einem alten Androiden fragen, das man per USB an den Server hängen kann...

E-Mail Account sollte vom Lab selber sein würde ich vorschlagen. Da ist normalerweise @waaaaargh für zuständig?

**Comment by phjlipp** [comment]
Ich meine, wir brauchen keine Packstation. Das ist so oder so personengebunden und wenn die leute was wollen, können sie sich selbst einen Account machen, dann muss man Postident und alles tun, das ist ein aufwand.

**Comment by phjlipp** [comment]
Nachdem das außerdem im Sand verlief und niemand danach schreit...
