### ISSUE TITLE
Neue gscheide Kabel für die 5.1-Anlage

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#148]
Die jetzigen haben Wackler & mindestens eine Box funktioniert nicht.

**Comment by moba** [comment]
Ich schließ das mal, 5.1-Sound scheint niemand zu brauchen, Stereo-Kabel ist erneuert worden, und ein MPD ist wieder am Start.

**Comment by Profpatsch** [comment]
Wir haben durchaus die Möglichkeit, den odroid mit 5.1 zu fahren, sogar mit einem optischen Kabel zur Anlage.

Ich würde das also noch offen lassen und in die Mediengschichte einbinden.

**Comment by Profpatsch** [comment]
Oh, wir haben noch einen eigenen Issue dafür. Dann close.
