### ISSUE TITLE
Wiki captcha funktioniert nicht

### ISSUE THREAD

**Issue by muesli** [openlab-aux/orgafoo#152]
Behauptet ich haette es falsch eingegeben. Auch nach 10 Versuchen ;-)

**Comment by moba** [comment]
Der Link "Registrieren" im Wiki führt inzwischen ins nichts: http://wiki.openlab-augsburg.de/ ganz unten "Registrieren?" -> Seit dem Umzug kaputt. https://wiki.openlab-augsburg.de/ ist auch kaputt, falsches Zertifikat.

=> wir brauchen dringend einen neuen Serveradmin. Anyone?

**Comment by moba** [comment]
Wiki ersetzt, Problem gelöst.
