### ISSUE TITLE
mpd mit ftp-Server vergschichteln

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#154]
Auf dem Server liegt ein Haufen Musik, das Zeug vom mpd ist größtenteils dupliziert davon.

Bei der Gelegenheit gleich mal beets drüberlaufen lassen?

**Comment by Profpatsch** [comment]
mpd läuft jetzt auf odroid und spielt auch Musik.

TODO:
- [ ] beets einrichten
- [ ] schreibbar machen
- [ ] System überlegen, wie man neue Musik drauflädt
- [ ] dokumentieren

**Comment by sternenseemann** [comment]
Gibt keinen mpd mehr
