### ISSUE TITLE
Kleinen neuen Schreibtisch aufbocken

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#156]
Bis Sonntag müssen wir wissen ,ob wir mehr von den geholten Schreibtischen haben wollen. https://www.quoka.de/gewerbe-business/bueromoebel/c8050a132474805/schreibtische.html

Es fehlen ein paar Zentimeter (wie viele?), dh. man müßte den einen "aufbocken" (bzw durchdenken wie wir das konkret machen würden) und dann überlegen ob wir mehr haben wollen.

**Comment by Profpatsch** [comment]
Ist wohl schon rum um’s Eck.

**Comment by moba** [comment]
Nicht zwingend. Angerufen? Es war zwar recht unfreundlich, dass wir ihm gesagt haben wir melden uns definitiv wieder sobald wie möglich, aber er meinte die stehen schon seit nem Jahr oder so rum und bisher wollte sie niemand. Kann also gut sein dass sie noch da sind.

**Comment by Profpatsch** [comment]
Haben momentan genug Tische.
