### ISSUE TITLE
Kodi-VM aufsetzen

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#159]
Am besten http://kodi.wiki/view/XBMCbuntu laufen lassen.

**Comment by waaaaargh** [comment]
On 03.01.2015 23:32, Profpatsch wrote:
> Am besten http://kodi.wiki/view/XBMCbuntu laufen lassen.

Nicht sicher, was das in einer VM ohne Grafikoutput bringen soll.
Elaborieren Sie.

**Comment by moba** [comment]
Also wir haben gestern diskutiert dass ein Indizierungsdingens für Musik und Filme sinnvoll wäre, mit dem man Filme dann über HTTP ans jeweilige Endgerät streamen kann, und vor allem Duplikate finden und gleich Metadaten von IMDB etc kriegt. XMBC wurde genannt, aber keine Ahnung ob das wirklich das richtige für den Einsatzzweck ist.

**Comment by sternenseemann** [comment]
Wollen wir das noch?

**Comment by Profpatsch** [comment]
kA, kann man ja bei Bedarf wieder öffnen.
