### ISSUE TITLE
Replace Kaercher manual with a Markdown version

### ISSUE THREAD

**Issue by aszlig** [openlab-aux/orgafoo#165]
Shouldn't be too much work, because it's very small document.

**Comment by richi235** [comment]
> Also, it shouldn't matter whether it's XeTeX or LaTeX and should be compatible to *both* (hey, it's a manual for a vacuum cleaner after all, so nobody should care about fancy fonts, right?).
Hue hue corporate identity huehuehue.

**Comment by Profpatsch** [comment]
Yay, it’s a vacuum cleaner manual, let’s use a typesetting system no one except a few cracks know how to use.

How about being sensible and doing it in Markdown or Asciidoc?

**Comment by aszlig** [comment]
@Profpatsch: Hm, in this case you're probably right and it's better to do in Markdown, especially if it comes to consistency with the other documents in the repository.

**Comment by aszlig** [comment]
In this case someone else probably wants to do it (probably someone using libreoffice so it's just copy & paste), because there are no `\"a`, `\"o`, `\"u` and `\ss{}` entities in Markdown.

**Comment by aszlig** [comment]
ah fuck it, i'll just do a search+replace afterwards :-)

**Comment by Profpatsch** [comment]
http://neo-layout.org/ :P

**Comment by aszlig** [comment]
@Profpatsch: I'm not switching to Neo just for the damn 3 to 4 German texts I usually write in a year :stuck_out_tongue_winking_eye:
