### ISSUE TITLE
labbee fixen

### ISSUE THREAD

**Issue by lukasepple** [openlab-aux/orgafoo#166]
Idlet ja bekanntlich nicht mehr in `#augsburg`. Vermutlich erst nach sphincter-Umzug sinnvoll…

**Comment by muesli** [comment]
Komm leider nich mehr per VPN auf die labbee VM. Nich sicher ob's am VPN oder am Server liegt.

**Comment by pRiVi** [comment]
Ja, das ist klar.

Rantanplan ist abgebaut und ich weiß nicht wie er angeschlossen ist.

Mir wurde die Kompetenz, am Netzwerk etwas machen zu dürfen, auch genommen. Darum kann ich das Problem auch nicht mehr lösen. Du wirst Dich wohl mit dem waaaaargh mal kurzschließen dürfen...

**Comment by muesli** [comment]
Ich kann das Ding auch bei mir zuhause laufen lassen, solange der Rest der Infrastruktur eh tot ist (labping, sphincter & co).

**Comment by muesli** [comment]
Ah, ne, das macht auch keinen Sinn, die Config ist ja auch auf der VM.

@waaaaargh Gib bitte bescheid wenn/falls/ob du Zeit hattest die VM zu fixen, und wie ich sie jetzt erreichen kann. Fuer Infrastrukturtreffen und Leuten hinterher rennen hab ich im Moment leider echt keine Zeit.

**Comment by moba** [comment]
labbee läuft
