### ISSUE TITLE
Neodym-Magneten trennen oder vermessen

### ISSUE THREAD

**Issue by phjlipp** [openlab-aux/orgafoo#167]
Da ich es ja in einem großen Fuckup mit Verletzung letstens dazu gebracht habe, die beiden Neodym-Magneten praktisch untrennbar miteinander zu verbinden, würde ich mich auch wieder der Trennung commiten. Dazu habe ich geplant, ein extra Werkzeug zu bauen, weil das ganze von Hand ja praktisch unmöglich ist. Hierfür bräuchte ich nun nur ungefähre Höhe und Durchmesser dieser Magneten. Dann könnte ich das neu geschaffene Tool gleich am 13. mitbringen (wenn ich eben das nächste mal da bin). Ansonsten muss das bis ins Unbestimmte warten.

Eine andere Option wäre, dass die irgendjemand anderes trennt, das wäre natürlich auch ok. Aber nachdem das ja mein Verschulden ist, ist es wohl auch meine Aufgabe, die Dinger wieder auseinenader zu kriegen.

**Comment by Profpatsch** [comment]
Zwei Rohrzangen ansetzen und mit dem generierten Hebel auseinanderdrücken?

**Comment by phjlipp** [comment]
Naja, ich fände so ein schönes Tool wäre die wesentlich elegantere Lösung, und Rohrzangen sind ja nun echt unhandlich... :D

**Comment by phjlipp** [comment]
Okay, 2,5cm*Durchmesser einer 1€-Münze wurde im IRC erwähnt, ich close das mal, mal sehen ob ich es schaffe das tool zeitig zu bauen...
