### ISSUE TITLE
Gefrierbeutel kaufen

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#169]

**Comment by phjlipp** [comment]
Immer noch aktuell? wenn ja, wie groß? 3l?

**Comment by Profpatsch** [comment]
Jo. 3l klingt gut.

**Comment by sternenseemann** [comment]
Passiert? @phjlipp

**Comment by phjlipp** [comment]
Für sowas statt einzelner issues einfach https://ola.pads.ccc.de/einkaufsliste-01 zu benutzen wäre sinnvoll, oder?

**Comment by sternenseemann** [comment]
Wenn das jemand anschaut.

**Comment by Profpatsch** [comment]
Tut es niemand. :)
