### ISSUE TITLE
Batterien

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#172]
Wir sollten Batterien für diverse Geräte anschaffen.

AA, AAA, …?

**Comment by phjlipp** [comment]
Die Tage mache ich jedenfalls eine Storage/Dispenser-ding dafür, das erscheint dann in der PartCloud. So gehen die Batterien wenigstens (hoffentlich) nicht on mass verloren \o/

**Comment by Profpatsch** [comment]
:+1:, momentan flacken sie überall einfach rum.

**Comment by phjlipp** [comment]
Okay, ich habe einen Tray for AA Baterien gemacht. Muss nur noch gedruckt werden. http://b2b.partcommunity.com/community/partcloud/index#!part?name=AA+Battery+tray&model_id=9209

**Comment by sternenseemann** [comment]
Status?
