### ISSUE TITLE
Fotos vom neuen Lab online bringen

### ISSUE THREAD

**Issue by iblech** [openlab-aux/orgafoo#173]
Auf http://wiki.openlab-augsburg.de/openwiki:raum sind noch die Fotos vom alten Lab zu sehen (und keine neuen). Und die Quadratmeterangabe ist auch noch nicht aktualisiert, oder?

**Comment by moba** [comment]
Die "neue" Anfahrtsbeschreibung ist ja unter https://openlab-augsburg.de/kontakt/ -- ich lösch das einfach mal ausm Wiki.

Fotos sind ein anderes Thema, aber ich find die gehören auch nicht ins Wiki, sondern auf eine sinnvollere Platform. Galerieplugins für Wordpress wurden mal diskutiert, hat sich aber bislang niemand gekümmert.

**Comment by grindhold** [comment]
fotos wurden in entsprechenden kategorien auf die webseite geladen. ("hauptraum", "werkstatt", "kueche", "bibliothek"
