### ISSUE TITLE
Passwortreset im Blog geht nicht

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#174]
Es wird keine Mail zugeschickt.

CC: @waaaaargh @moba @michiwend

**Comment by moba** [comment]
Reverse DNS korrekt gesetzt, hostname in /etc/hosts eingetragen -> sollte jetzt gehen. Ich sehe eine gute Spamflut auf uns zukommen weil sich nach wie vor flessig Spamaccounts im Wordpress einen Account einrichten...
