### ISSUE TITLE
Gaffer-Tape besorgen

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#175]
Ich wär mal für ne Großbestellung. Mag jemand ne billige Quelle jagen? Mydealz, eBay, kA.

**Comment by waaaaargh** [comment]
Thomann: http://www.thomann.de/de/stairville_gaffa_400bk.htm
Billigster Ebayer: http://www.ebay.de/itm/Gewebeklebeband-48mm-x-50m-silber-Steinband-Panzertape-Panzerband-Gaffa-Gaffer-/271693811985?pt=LH_DefaultDomain_77&hash=item3f42369111

Unter EUR 3 / 50m geht da nicht so viel meiner Erfahrung nach.

**Comment by Profpatsch** [comment]
@moba hat glaub ich gestern ein ziemlich billiges Angebot gefunden, eher Richtung <2€.

**Comment by moba** [comment]
Das war das hier: http://www.ebay.de/itm/Gewebe-Allzweck-Klebeband-SILBER-50mm-x-50m-Panzerband-Duct-Tape-24-Rollen-/291492290288

24 Rollen für 45€ => 1,875€

Kann das aber nicht bestellen, weil mein Paypal nicht funktioniert.

**Comment by Profpatsch** [comment]
Done.
