### ISSUE TITLE
Switch für Arbeitstisch

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#177]
Momentan ist da ein 100Mbit/s Hub. Das ist zwar schön klein, aber hat keinen Durchsatz. Genau den will man aber, wenn man Ethernet anschließt.

Am besten einen kleinen Switch finden, der 1Gbit/s macht.

**Comment by momo-aux** [comment]
Hab einen kleinen 5 port gigabit, für 15€ wenn jemand den bezahlt bring ich ihn mit.

**Comment by pRiVi** [comment]
Der aktuelle 100 Mbit/switch läßt VLANs durch, bitte durch was VLAN fähiges ersetzen.

**Comment by sternenseemann** [comment]
Noch aktuell? Gibt auf jedem Tisch einen Switch.
