### ISSUE TITLE
spiegel montieren

### ISSUE THREAD

**Issue by devkral** [openlab-aux/orgafoo#179]
Hab einen Spiegelschrank mitgebracht. Badezimmerspiegelproblem lässt sich nun einfach lösen.
Müsste halt nur jemand machen (ich hab keine Ahnung von den Wänden).

**Comment by moba** [comment]
Den Spiegelkasten hat nach wie vor niemand aufhängen wollen. Es hat sich in der zwischenzeit ein einfacher Spiegel eingefunden, hab ich mal mit doppelseitigem Klebeband aufgehängt.

**Comment by grindhold** [comment]
fettes display wurde als spiegel repurposed. kann als erledigt betrachtet werden
