### ISSUE TITLE
60l Müllsäcke

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#180]

**Comment by glaxx** [comment]
Sind leer? Sind voll? Du steckst in einem?

*Bitte mehr Infos.*

**Comment by Profpatsch** [comment]
Nachkaufen natürlich. :)

**Comment by moba** [comment]
Kann ich mir gar nicht vorstellen. Im Lager im Bad hast du geschaut?

**Comment by Profpatsch** [comment]
Sind soweit ich gesehen habe nur noch >=120l vorhanden. Hab die anderen nicht-grünen stichprobenartig durchprobiert.

**Comment by moba** [comment]
Ja stimmt das kann gut sein.

**Comment by moba** [comment]
3x20 gekauft und im Meerjungfrauenbad bei den anderen Müllsäcken deponiert.
