### ISSUE TITLE
Küchenschränke (III): Reste zusammenstellen und dann entsorgen

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#185]
Die restlichen nicht verwendeten Teile der Küche sollten zusammengetragen und entsorgt werden. Beispielsweise könnte man einen Termin für Sperrmüll beantragen und dort die abzuholenden Teile beschreiben, dann zum Termin an die Straße stellen, das ist kostenlos.

**Comment by Profpatsch** [comment]
Link: http://www.abfallratgeber.augsburg.de/index.php?id=35308
