### ISSUE TITLE
Klobürsten kaufen

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#186]
Ich fände es schön, wenn wir /weiße/, große Klobürsten hätten. Die, die in eine Halterung hängen und nicht in ihrem eigenen … Schweiß stehen.

2 Stück und besser gleich zwei Ersatz (sollten (halb-)jährlich ausgetauscht werden).

**Comment by moba** [comment]
Vor ner Weile hab ich das gemacht. Wie gewünscht weiß und hängend. Gabs bei Aldi.

**Comment by Profpatsch** [comment]
thx!
