### ISSUE TITLE
Klopapier alle

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#187]
Noch 2–3 Rollen, dann ist Sense.

**Comment by moba** [comment]
Ist nach wie vor schade dass scheinbar niemand diesen Issuetracker verfolgt oder nicht danach handelt. Aber Kackapokalypse ist ferner als du denkst, und damit das auch mal dokumentiert ist hier der Klopapierlagerplatz in Bild dokumentiert:

![null](https://cloud.githubusercontent.com/assets/347406/9406349/11221b50-4800-11e5-8917-f1a0ab51d93e.jpeg)

(im Meerjungfrauenbad das Regal gleich rechts, oberstes Fach)
(dennoch kann und sollte gerne Klopapier gekauft werden, deshalb lasse ich das mal noch offen)

**Comment by Profpatsch** [comment]
Nett, habe ich übersehen. Weiß auf weiß und so. :)

**Comment by verbosemode** [comment]
Ich kenne den üblichen Durchsatz nicht, aber ich habe jetzt 4 x 10 mitgebracht und im Bad positioniert.
