### ISSUE TITLE
Mikrofaserlappen für Bäder besorgen

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#188]
Die billigen Schwammtücher verschmieren den Dreck mehr als ihn aufzunehmen. [Hiermit](http://www.amazon.de/Ha-Ra-Viva-Ultra-Putzlappen/dp/B00H0AMUQ0/ref=sr_1_1?ie=UTF8&qid=1440018115&sr=8-1&keywords=hara+lappen) habe ich gute Erfahrungen gemacht, gibt aber bestimmt auch billigere gute Alternativen.

**Comment by robinkaranu** [comment]
Außreichende Menge scheint vorhanden, allerdings andere, wohl von einem Supermarkt.
