### ISSUE TITLE
Kabelreste entfernen

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#190]
Wir haben jetzt Außendosen (yay!). Dabei haben die Bauarbeiter ein paar unserer LAN-Kabel durchschnitten (noes!).

Dank heldenhaften Einsatzes wurde die Internetsituation erstmal kurzfristig gelöst und jetzt in eine doch wohl mittelfristige Lösung überführt. Dabei wurde nun unter anderem von einer Außendose ein freischwebendes LAN-Kabel zu den Nanostations am Zaun geführt.

Die Reste mehrere Kabel gammeln da noch so rum und schauen unschön aus.

Frage am Rande: Wir könnten die Nanostations jetzt eigentlich auch auf unser Gebäude umziehen, oder?

**Comment by lukasepple** [comment]
Ist da nicht eventuell eine Baum-Im-Weg-der-wächst-Problematik?

**Comment by pRiVi** [comment]
Ja, also das Signal, insbesondere bei 5 ghz, ist schlechter wenn es Matrie durchdringen muß. Ausserdem ... wohin auf unser Gebäude? Wer kann da wie hin und es dort anbringen?

Um die Kabelreste kümmere ich mich innerhalb der nächsten Tage.

**Comment by sternenseemann** [comment]
Sollte passiert sein, oder? Schließe mal
