### ISSUE TITLE
Toilette verstopft // Saugglocke benötigt

### ISSUE THREAD

**Issue by glaxx** [openlab-aux/orgafoo#194]
Die Einhorntoilette ist verstopft. Leider befindet sich auch keine Saugglocke im Lab.

**Comment by waaaaargh** [comment]
could not reproduce

**Comment by Profpatsch** [comment]
Das ging bestimmt mit einem beherzten Griff ins Klo. :)

**Comment by lukasepple** [comment]
wat

**Comment by glaxx** [comment]
Hat sich wohl erledigt.
