### ISSUE TITLE
Spaceapi down

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#195]
Die Spaceapi ist generell down (siehe https://github.com/slopjong/OpenSpaceDirectory/issues/31).

Unsere json-Datei benutzt gerade noch nicht den neuen Sphincter. cc @waaaaargh

**Comment by pRiVi** [comment]
Tja, das passiert wenn man auch die kleinsten Tasks gleich mit API und CLOUD machen muss, statt es einfach so mit eigenen unkomplizierten Mitteln zu machen

**Comment by Profpatsch** [comment]
@pRiVi Das ist eine Datei, die alle paar Minuten von einem cronjob auf einem Server generiert wird.

**Comment by lukasepple** [comment]
lol

**Comment by pRiVi** [comment]
Scheint wieder zu klappen?

**Comment by lukasepple** [comment]
Ich öffne das mal als Issue in dem Spaceapi repo, spaceapi.net hat das Problem gefixt.

**Comment by Profpatsch** [comment]
Ja, nur unsere API funzt immer noch nicht, weil sie nicht von Sphincter die Daten holt. Da muss sich der @waaaaargh drum kümmern.

**Comment by lukasepple** [comment]
Siehe issue in dem [korrekten repo](https://github.com/openlab-aux/spaceapi/issues/6)

**Comment by Profpatsch** [comment]
Macht Sinn.
