### ISSUE TITLE
Ofen anschließen

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#198]

**Comment by waaaaargh** [comment]
Muss AFAIK eine Elektrofachkraft machen, dürfen wir nicht selbst.

**Comment by lukasepple** [comment]
In der Tat.

**Comment by moba** [comment]
Sollte aus versicherungstechnischen Gründen eine Fachkraft machen. Elektriker steht auf der Telefonliste der Handwerker, mit dem sollte man mal sprechen.

**Comment by Profpatsch** [comment]
Wer ruft ihn an?

**Comment by glaxx** [comment]
Trägt der Verein die Kosten davon?

**Comment by moba** [comment]
Ich denke der ist eh mal in der Gegend und macht das für sehr günstig bis umsonst. Kann mich nur momentan nicht drum kümmern weil ich ständig unterwegs bin.

**Comment by moba** [comment]
Vorarbeit könnte man aber leisten, also sicherstellen dass die Kabel alle zugänglich und ausreichend lang etc sind. Wenn ich mich richtig erinnere wurde das ja einfach nur so hin- und zugestellt.

**Comment by moba** [comment]
Hat der Weihnachtsmann fachgerecht angeschlossen und funktioniert jetzt!

**Comment by lukasepple** [comment]
Dem Weihnachtsmann ewige Blumenkraft!
