### ISSUE TITLE
port 17 (ethernetdose sofaecke) werkt nicht

### ISSUE THREAD

**Issue by grindhold** [openlab-aux/orgafoo#202]
An dieser dose eingesteckte Geraete erhalten keine sinnvolle IP.  Das kabel scheint korrekt aufgepatcht zu sein. Ich vermute konfigurationsfoo im switch. Kabeldefekt ist nicht auszuschliessen.

**Comment by verbosemode** [comment]
Dose 17 und 18 sind gepatcht und funktionieren

$ ip addr show
...
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.178/16 brd 172.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever

172.16.0.2 / 172.16.0.1 sind per Ping erreichbar

$ ping -I eth0 172.16.0.2
PING 172.16.0.2 (172.16.0.2) from 172.16.0.178 eth0: 56(84) bytes of data.
64 bytes from 172.16.0.2: icmp_seq=1 ttl=64 time=0.737 ms
64 bytes from 172.16.0.2: icmp_seq=2 ttl=64 time=0.779 ms
64 bytes from 172.16.0.2: icmp_seq=3 ttl=64 time=0.770 ms
64 bytes from 172.16.0.2: icmp_seq=4 ttl=64 time=0.763 ms

Mit Tcpdump sieht man auch, dass man evtl im richtigen VLAN ist, weil Hosts aus dem Netz 172.16.0.0/16 zu sehen sind.

22:05:48.776873 IP (tos 0x0, ttl 64, id 17724, offset 0, flags [DF], proto UDP (17), length 84)
    172.16.0.150.41635 > 172.16.255.255.21025: UDP, length 56
	0x0000:  4500 0054 453c 4000 4011 9ca6 ac10 0096  E..TE<@.@.......
....

**Comment by Profpatsch** [comment]
Dann passts ja.
