### ISSUE TITLE
Küche: Messermagnetleiste

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#203]
Eine Magnetleiste für Messer wäre gut; momentan liegen sie in der Schublade und machen sich gegenseitig stumpf.

**Comment by phjlipp** [comment]
Ich kümmere mich um die Beschaffung, im laufe der kommenden Woche liegt die dann zum einbau in der Küche (das muss jemand anderes machen dann, wenn ich einen Bohrer in die Hand nehme, ist am ende bestimmt die wand kaputt)

**Comment by phil-underscore** [comment]
Wenn eine entsprechende Leiste beschafft wird, bau' ich sie ein. Ich hab kürzlich erst passende Hohlwanddübel besorgt.

Für zeitnahes DIY seh ich gerade schwarz, das hat in der Vergangenheit leider auch höchstens mittelmäßig funktioniert.

**Comment by Profpatsch** [comment]
+1 für gekaufte Leiste (ist eh nur ein magnetisierter Streifen Metall).

**Comment by phil-underscore** [comment]
Also wie gesagt, prinzipiell ist mir egal wo die Leiste herkommt. Wenn sie in der Küche liegt, bau' ich sie ein. 
Aber mit Beschaffung/Bau der Leiste möchte ich mich gerade nicht auch noch befassen, bin im Moment an anderen Infrastrukturprojekten dran.

**Comment by Profpatsch** [comment]
Dann würde ich sagen Bühne frei für @phjlipp. :)

**Comment by phil-underscore** [comment]
Wie ist denn grad der Status? Bei Lidl gibts im Moment Magnetleisten für 3€ *nursagend*

**Comment by phjlipp** [comment]
Eine hätte ich schon gekauft rumliegen hier. (Aber nicht die von lidl, im
Zweifel schicke ich sie wieder zurück)
Peb sollte am Samstag irgendwann neodym-magnete ins lab gelegt haben, um
daraus eine authentischere magnetleiste werden zu lassen. Ich fahre gleich
hin und schau, ob ich die finde. Dann konstruiere ich die nötige
Halterung.

**Comment by Profpatsch** [comment]
@phjlipp Wie ist denn der Status des Projekts?

**Comment by phjlipp** [comment]
Ist fast fertig, muss das Teil eigentlich nur noch 2 mal drucken und mir
eine Lösung zum festkleben ausdenken.

**Comment by sternenseemann** [comment]
Wie ist der Status hier?

**Comment by phjlipp** [comment]
Ich würde das mit gekauften Leisten auf neuaufbau der Küche verschieben, da die DIY-Leisen scheuslich unterperformen.

**Comment by sternenseemann** [comment]
Ah #243.

**Comment by robinkaranu** [comment]
not applicable
