### ISSUE TITLE
Küche: Arbeitsflächenbeleuchtung

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#204]
Wir haben an einen LED-Streifen unter den Schränken und an einem unter dem Fensterbrett gedacht.

**Comment by phil-underscore** [comment]
Wenn man mir das Material besorgt bau' ich das ein. Ich würde auch gleich noch einen unter die Bar setzen.

**Comment by Profpatsch** [comment]
Können wir da so einen 1–2s Ein- und Ausfadeeffekt einbauen? :)

**Comment by phil-underscore** [comment]
Kann man machen, ja.

**Comment by lukasepple** [comment]
Trivial PWM :D

**Comment by moba** [comment]
Einkaufsliste mit Preisen in Ethercalc, krautfunden!

**Comment by Profpatsch** [comment]
@phil-underscore Hast du einen Vorschlag, was wir da am besten nehmen? Und welche Bauteile wir brauchen? Netzteil?

**Comment by phil-underscore** [comment]
Das kommt drauf an, ob man das als Akzentbeleuchtung oder echtes Arbeitslicht haben will. In ersterem Fall tuts jeder billige Streifen von Ebay, in letzterem möchte man schon etwas mehr Geld in die Hand nehmen und einen leistungsstarken Streifen kaufen.

Die LED-Streifen in der E-Ecke sind 24V-Streifen mit 1140 Lumen/Meter. Die haben aber auch 70€ gekostet.

Wir haben auch noch drei Leuchtstoffröhren vom Robin, die sind allerdings ohne Abdeckung (nicht bruchgeschützt) mMn. für die Küche eher ungeeignet.

**Comment by Profpatsch** [comment]
Definitv Arbeitslicht; wir brauchen nicht dieselbe Lumenleistung wie die E-Ecke, aber die indirekte Beleuchtung vom Raum reicht in der Küche nicht wirklich.

Vllt. auch ein leicht wärmeres Licht als in den E-Ecke?

**Comment by phil-underscore** [comment]
Ok, warmweiße 12V-Streifen. Ich hab mal nachgemessen, wir brauchen 6.5m inklusive Bar. Möglich, dass das zu dunkel ist, dann bräuchten wir doppelt so viel Streifen und verlegen einfach zwei Stück nebeneinander.

Bei zwei Streifen nebeneinander ist eine 12V-Versorgung allerdings sehr schwer, da sind wir im Bereich von ~13A.

Man könnte z.B. sowas hier nehmen:
http://www.ebay.de/itm/5M-5630-5050-2835-3528-LED-Strip-Stripe-Streifen-Lichtketten-Fernbedienung-Trafo-/291228718384?var=&hash=item43ce959530

-warmweiß
-wasserdicht
-mit 5A Trafo
-LED-Bauform 5050

Macht zusammen 40€.

**Comment by sternenseemann** [comment]
Wie ist der Status hier?

**Comment by Profpatsch** [comment]
Will man noch haben, hat nur noch keiner gemacht.

**Comment by robinkaranu** [comment]
not applicable
