### ISSUE TITLE
Kalendereinträge falsch/doppelt etc

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#207]
Kann sich bitte jemand mal dem Problem des Kalenders annehmen? Ich poste das mal hier rein, ich hab das Gefühl das website-Repo sehen noch weniger Leute... https://github.com/openlab-aux/website/issues/2

**Comment by waaaaargh** [comment]
Ich hab mal ein bisschen rumgeschaut, muss entweder ein vollkommen obskurer Datenbankfehler oder ein Bug im Events-Plugin sein. Tempfix von meiner Seite war:
  * Wiederkehrende Veranstaltung "offener Abend" gesplitted: einmal bis zum 21.10.2015 und einmal ab dem ersten Mittwoch im November. Der 28.8. wurde vom Events-Plugin immer auf Dienstag, den 27. verschoben (siehe http://imgur.com/gj1Vl57), daher habe ich den am 28. händisch angelegt. 
  * Sämtliche Wiederkehrende Events, die das nächste mal erst im November stattfinden, habe ich aktualisiert, sodass der wiederkehrende Event erst wieder im November beginnt.

Die Merkwürdigkeiten scheinen alle mit Daten Ende Oktober verbunden zu sein, nicht sicher was da abgeht.

**Comment by sternenseemann** [comment]
Nicht wieder aufgetreten, oder?

**Comment by Profpatsch** [comment]
Der Kalender generiert einzeln Termine von einem „wiederkehrend“ Template. Wenn das zu lange dauert (zu viele Termine auf einmal) macht PHP ein Time-out und der ganze Rotz hängt im Kalender. Völlig hirngeschädigt, aber mei. Was will man erwarten.
