### ISSUE TITLE
Getränke alle

### ISSUE THREAD

**Issue by phjlipp** [openlab-aux/orgafoo#208]
Habe gerade die noch vorhandenen Reste in Kühlschrank geräumt, der ist jetzt gut halb voll. Danach haben wir nichts mehr. Es wäre empfehlenswert, möglichst schnell Nachschub zu holen, entsprechend viele Pfandkästen stapeln auch schon vorsortiert vorm Eingang.

**Comment by Profpatsch** [comment]
Sicher vorsortiert?

**Comment by glaxx** [comment]
Nicht alle davon waren vorsortiert. Gerade bei Club Mate Kästen muss man aufpassen.

Aber nichts desto trotz hat das Labor wieder eine Fuhre Getränke.

Leute, denkt daran eure Getränkeschulden zu bezahlen, **sobald** die Getränke knapp werden.
