### ISSUE TITLE
Lab für offenen Abend vorbereiten

### ISSUE THREAD

**Issue by phil-underscore** [openlab-aux/orgafoo#209]
Das Lab sieht schon wieder richtig schlimm aus. Aufräumen für morgen abend wäre sinnvoll.

**Comment by phil-underscore** [comment]
Die Klos sind immernoch so versifft wie vor zwei Wochen, im Hauptraum wurde auch nix aufgeräumt.

Schade.

**Comment by Profpatsch** [comment]
Wir haben jetzt beim Curry Club alles ein bisschen komprimiert hingestellt und den Boden in der Mitte des Raumes gekehrt.

Klos sind glaub ich noch nicht geputzt.

**Comment by grindhold** [comment]
dieser konkrete abend ist vorbei. ich mache die issue zu.
