### ISSUE TITLE
Soundanlage abbauen

### ISSUE THREAD

**Issue by phil-underscore** [openlab-aux/orgafoo#210]
Die Anlage von der NN2 steht immernoch und ist im Weg. Bitte abbauen!

**Comment by phil-underscore** [comment]
Die Anlage steht immernoch. Wer hat denn da den Hut auf?

**Comment by glaxx** [comment]
Ich glaube die Anlage gehört dem Bene. Hab leider keine Kontaktmöglichkeit, könnte aber beim Abtransport der Anlage mit meinem Auto behilflich sein.

**Comment by Profpatsch** [comment]
Hab gestern mit dem Bene geredet. Er nimmt sie jederzeit, wir müssen sie nur in ein Auto packen, das groß genug ist (er selbst hat keins).

Hat jemand ein Auto?

**Comment by sternenseemann** [comment]
Noch aktuell?

**Comment by Profpatsch** [comment]
Nope, schon lange weg.
