### ISSUE TITLE
Müllbeutel

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#213]
* 30l (2–3 Rollen)
* sehr klein (5l?) für Mülleimer im Bad

**Comment by Profpatsch** [comment]
Es scheinen eventuell noch 30l-Beutel in einer anderen Farbe (nicht weiß) da zu sein, das müsste man noch nachkontrollieren.

**Comment by Profpatsch** [comment]
Wieder aktuell: Wir brauchen 60l Beutel (5–10 Rollen) und 30l Beutel (3–5 Rollen).

**Comment by PenguWin** [comment]
Habe welche gekauft

**Comment by Profpatsch** [comment]
Wir brauchen aber noch einige mehr. Die drei Rollen halten keinen Monat, leider.

**Comment by moba** [comment]
Reminder: Belege Richtung Vorstand, dann gibts das Geld zurück. :)

**Comment by sternenseemann** [comment]
Dem Pad von #230 hinzugefügt.
