### ISSUE TITLE
Verstärker brummt ekelig

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#214]
Seit 1–2 Wochen brummt der Verstärker auf einer relativ hohen Frequenz. Was könnte das sein?
Ist schon fast kopfschmerzverursachend.

**Comment by phjlipp** [comment]
laut $Leuten kennt total1ty einen fix dafür.

Am 1. November 2015 um 23:05 schrieb Profpatsch <notifications@github.com>:

**Comment by lukasepple** [comment]
Ging, eher um das Piepsen.

**Comment by phjlipp** [comment]
naja, eines tut ein solcher verstärker wohl einfach, das andere (deutlich
nervigere) ist hoffentlich fixbar.

2015-11-01 23:36 GMT+01:00 sternenseemann <notifications@github.com>:

**Comment by Profpatsch** [comment]
Fix’d, aufgeschraubt und es war weg. #thatWasEasy

**Comment by Profpatsch** [comment]
Okay, volle Kraft zurück. Er hat wieder angefangen.
