### ISSUE TITLE
Musikanlage dokumentieren

### ISSUE THREAD

**Issue by phjlipp** [openlab-aux/orgafoo#216]
ich kann nur die alte version des musikservierers vom profpatsch, wie kriege ich als dummie den mpd gerade wieder schnell zum laufen, wenn der odroid gerade mal abgekackt ist?

**Comment by Profpatsch** [comment]
Ausstecken, einstecken?

**Comment by lukasepple** [comment]
Es geht um Dokumentation im Wiki:

* IP
* Zugang
* Konfiguration (von mpd und clients)

**Comment by pRiVi** [comment]
IP: Steht am Zettel überall
Zugang: SSH
Konfiguration:
  mpd: default
  clients: default

**Comment by lukasepple** [comment]
Wiki!

**Comment by pRiVi** [comment]
IRC!

**Comment by lukasepple** [comment]
Hier nochmal die Bitte das einfach im Wiki zu dokumentieren.

**Comment by Profpatsch** [comment]
+1

**Comment by Profpatsch** [comment]
mpd & Gschichte ist grad im Flux (pulseaudio streaming!). Wenn soweit fertig, werde ich das dokumentieren.

**Comment by sternenseemann** [comment]
Ich werde das im neuen Wiki dokumentieren

**Comment by Profpatsch** [comment]
yay

**Comment by Profpatsch** [comment]
joa.
