### ISSUE TITLE
Drucker im OpenLab

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#219]
Es ist ja schon manchem aufgefallen daß bei uns einige Drucker gewachsen sind. Frohe Nachrichten: Wir haben jetzt noch vier neue!

Wer sich wundert was damit passiert, und sich schon fragt ob die Drucker denn auch ihren Mitgliedsbeitrag zahlen für die Raumnutzung: Drei der neuen Drucker sind zum Ausschlachten für die Roboterworkshops, da ist der Zuständige der Robin, die Überreste werden nächste Woche vom Momo dankenswerterweise entsorgt. Der vierte neue, der HP Color Laserjet, ist Teil der "wir finden einen Drucker mit Einzugs-Duplexscanner"-Abenteuer, zu dem auch die beiden dickeren Teile unter dem Panaboard gehören. 

Beim schicken dicken Sharp (rechts) wurde eine kleine Klappe irgendwohin verräumt, hoffentlich auch mit den zugehörigen Schrauben (das lag beides oben auf dem Drucker). Wenn diese Teile wieder gefunden werden kann man den zusammenbauen, dann können wir den wieder verkaufen: Der wurde gekauft (mit Geld), weil er eigentlich toll wäre, wenn denn der Duplex-Einzugsscan funktionieren würde. Hunz hat sich heldenhaft bemüht die Firmware zu analysieren, aber wir geben das wohl auf und er kommt wieder weg.

Der Toshiba links daneben war eine Spende, er müßte mal zusammengebaut werden, da liegen ein paar Teile daneben, dann könnte man ihn durchtesten und dann auch wieder verticken oder verschenken. Den gibt es als potentielle Alternative zum Sharp, so wegen Einzugscanner und so.

Bei dem HP funktioniert das Scannen an sich, aber irgendwas stimmt nicht mit dem Einzug.

TODOS: 

 - HP: Einzug prüfen und fixen
 - Sharp: Klappe finden und zuschrauben
 - Toshiba: Zusammenbauen und testen

Danach sind wir die dann allesamt wieder los bzw. können entscheiden ob wir den HP zum Labdrucker/scanner erklären und den reinen Drucker (Lexmark) wegtun weil Platzmonster.

**Comment by moba** [comment]
Der Toshiba wurde inzwischen wegen Toner-Spillage entsorgt. Der Einzug des HPs geht nach wie vor nicht, die Klappe des Sharps ist nach wie vor nicht aufgetaucht.

**Comment by Profpatsch** [comment]
Uralt
