### ISSUE TITLE
http://wiki.openlab-augsburg.de/ führt noch auf die alte Website!

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#220]
http://wiki.openlab-augsburg.de/

sollte führen auf: http://wiki.openlab-augsburg.de/openwiki:start

cc @waaaaargh

**Comment by lukasepple** [comment]
+1

**Comment by sternenseemann** [comment]
Einfach mit dem neuen Wiki bald™ ersetzen.

**Comment by moba** [comment]
Wurde ersetzt.
