### ISSUE TITLE
Website: Fußweg vom Bahnhof

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#221]
http://www.yournavigation.org/?flat=48.365111387704&flon=10.887192758475&tlat=48.3577357&tlon=10.8867806&v=foot&fast=0&layer=mapnik zeigt _fast_ den wohl besten Fußweg vom Hauptbahnhof zum Lab. Wenn man dort nochmal auf "shortest" klickst dann paßt es. Man kann dort ein .gpx exportieren, das kann man wahrscheinlich bei uns dort wo die Karte angezeigt wird z.B. mit diesem Plugin https://www.mapbox.com/mapbox.js/example/v1.0.0/omnivore-gpx/ mit reinladen. Vielleicht will sich da ja mal jemand drum kümmern?

**Comment by sternenseemann** [comment]
Die Website ist grade irgendwie kaputt, kann kein gpx generieren :(

**Comment by sternenseemann** [comment]
Ich kann kein GPX exportieren, geht das bei dir?

**Comment by moba** [comment]
Nicht mal die Wegzeichnung klappt bei mir noch auf der Seite. Aber man wird sicherlich noch andere Seiten oder Werkzeuge finden dafür.

**Comment by sternenseemann** [comment]
Okay, dann schaue ich mal

**Comment by phjlipp** [comment]
@sternenseemann dann schau doch bitte mal! :\

**Comment by sternenseemann** [comment]
Habe ich und die Website funktioniert nicht ordentlich, weitere Untersuchungen haben bisher nichts ergeben.

**Comment by sternenseemann** [comment]
Habe bis jetzt noch nichts gefunden, als Übergangslösung könnte man vllt. ein SVG / PNG erstellen.

**Comment by moba** [comment]
Man braucht auch keine Routing-Geschichte für den einfachen Weg, ein Overlay mit ein paar Strichen würde ja für uns ausreichen. Das im Threadstart war (damals) ne Website die einem halt so Routen exportieren erlaubt hat. Da gibts schon verschiedene andere Tools mit denen man solche Karten erzeugen kann (zB via https://wiki.openstreetmap.org/wiki/Routing). Fänd ich angebrachter als was statisches ohne Zoommöglichkeit usw. -- aber, ja, wenns denn sein muss... Ne Übergangslösung wird halt bei uns sofort zur Dauerlösung. Und dann sehen wir endgültig wie ein Gartenzwergzüchterverein aus.

**Comment by moba** [comment]
Paar Minuten googlen: http://openrouteservice.org/ , schick, hat GPX export, findet sofort den Fußweg.

**Comment by sternenseemann** [comment]
* <https://sternen.space/tmp/openlab-vom-bahnhof.gpx>
* <https://wiki.openstreetmap.org/wiki/Openlayers_Track_example>

mach ich bald™

**Comment by robinkaranu** [comment]
Neues Lab, neue Kartenbedarfe.
