### ISSUE TITLE
Außenknauf fast ab

### ISSUE THREAD

**Issue by devkral** [openlab-aux/orgafoo#222]
Der Knauf draußen an der Eingangstür ist mittlerweile ziemlich locker. Bitte befestigen, bevor ab!

**Comment by Profpatsch** [comment]
Haben wir erst vor kurzem manuell wieder festgeschraubt.

Ist der schon wieder locker? Die Eingangstüre ist schon ein billiges Stück Cowertarbeit.

**Comment by moba** [comment]
Fixed with self-3d-printed Eingangsknauf. \o/
