### ISSUE TITLE
Ungepatchte Felder

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#223]
Es ist 2016. Im Openlab gibt es immer noch ungepatchte RJ45-Buchsen im Kabelkanal.

Konkret die Dose links von der E-Ecke, aber ich kann mir vorstellen, dass auch weitere betroffen sind.

**Comment by phil-underscore** [comment]
Das liegt daran, dass wir mehr Dosen als Kabel in der Wand haben. Als 
Kompromiss haben wir deswegen unter dem mittleren und dem rechten 
Fenster nur jeweils eine der beiden Buchsen angeschlossen.

Möglich, dass das seitdem geändert wurde. Wenn mans genau wissen will 
muss man im Kanal schauen welche Buchsen angeklemmt sind.

Am 24.01.2016 um 18:52 schrieb Profpatsch:

**Comment by Profpatsch** [comment]
On 16-01-24 10:04am, phil-underscore wrote:
> Das liegt daran, dass wir mehr Dosen als Kabel in der Wand haben. Als 
> Kompromiss haben wir deswegen unter dem mittleren und dem rechten 
> Fenster nur jeweils eine der beiden Buchsen angeschlossen.

Hm, sollte man auf den Dosen halt auch so kommunizieren.

Warum patchen wir das nicht richtig? Waren die Kabel zu teuer?

-- 
Proudly written in Mutt with Vim on NixOS.
Q: Why is this email five sentences or less?
A: http://five.sentenc.es
May take up to five days to read your message. If it’s urgent, call me.

**Comment by phil-underscore** [comment]
Für die Details welche Dosen genau betroffen sind darfst du die Menschen 
fragen, die vor dem Einzug das Netzwerk gemacht haben.

Es wurden halt nicht genug Kabel während des Baus gelegt, das ist der 
ganze Grund. Wenn sich jemand bereit erklärt den gesamten Boden 
rauszunehmen (Auch: Serverschrank und alles an Netzwerkinstallation da 
drin abbauen) und neue Kabel zu verlegen, dann können wir auch die zwei 
unbelegten Dosen aufklemmen.

Am 25.01.2016 um 13:03 schrieb Profpatsch:

**Comment by momo-aux** [comment]
oder aufsplitten und mit 100mbit beschriften.
Dann kein Kabelfoo ist nötig, junger Pachdawan.

**Comment by Profpatsch** [comment]
kA wie man das macht. Aber da sollte sich die Netzwerkundigen drum kümmern (und mir das am besten gleich zeigen)

**Comment by grindhold** [comment]
@Profpatsch 100Mbit-Ethernet braucht nur 4 adern von den 8 die im kabel sind. 
Kabel splitten und auf die dosen neu auflegen und serverschrankseitig auf zwei stecker verteilen und neu zusammencrimpen - fertig.
Die Kabel haben praktischerweise farbcodierungen, viermalmal in gestrichelt und viermal in durchgezogen. Auseinanderhalten der adern sollte also kein problem sein.

**Comment by momo-aux** [comment]
Für 100 mbit braucht man 4 Adern, genauer gesagt die Adern 1,2,3 und 6
(im RJ 45 Stecker) sind belegt.

Ich schliesse die dann immer so an (ist aber relattv egal, hauptsache
man schliesst beide Seiten gleich an:

01 02 03 04 05 06 07 08
a1 a2 a3 b1 b2 a6 b3 b6

Falls es wen interessiert, ich mach da immer 568A Standard, das bedeutet:

01 grün/weiß
02 grün
03 orange/weiß
04 blau
05 blau/weiß
06 orange
07 braun/weiß
08 braun

Ich empfehle Netzmafia mal zu lesen:
http://www.netzmafia.de/skripten/netze/twisted.html

In diesem Sinne, let's twist again! ;-)

Bin nachher im Lab (gegen 20:00), wenn mir jemand zeigt, was wo hin
soll, dann kümmer ich mich drum.


Am 26.01.2016 um 14:52 schrieb Profpatsch:

**Comment by pRiVi** [comment]
Hm... Ich weiß nicht ob wir wirklich Gigabit auf ein zehntel dafür reduzieren wollen?

**Comment by sternenseemann** [comment]
Wollen wir hier etwas tun? 100MBit/s ist insgesamt nicht erstrebenswert imo.

**Comment by robinkaranu** [comment]
Es ist 2022, der Switch wurde abgebaut.
