### ISSUE TITLE
sphincter-repos konsolidieren

### ISSUE THREAD

**Issue by grindhold** [openlab-aux/orgafoo#225]
Wir haben zig repos, die alle irgendwie sphincter2-relatiert sind. Das muss in ein einziges repo ueberfuehrt werden. Auch sind teils noch alte entwuerfe fuer die CAD-gschichtn drin, die ueberholt wurden. 
Mein Vorschlag:

Ein Repo mit folgenden ordnern:
- CAD - openscad sourcen und stl-files
- code - ordner mit unterordnern, der den code der verschiedenen sphincter-softwarekomponenten enthaelt
- pcb - platinendesigns, gerberfiles und co
- legacy - verworfene cad- und pcb-designs und verworfener code

**Comment by lukasepple** [comment]
:+1:

**Comment by sternenseemann** [comment]
Konsolidieren heißt hier doch einfach, das schon angelegte [meta-repository](https://github.com/openlab-aux/sphincter2) fertig zu machen. Ich würde das gerne machen, wenn mir jemand versichern kann, das das so passt, wie ich das machen will:

* cad -> <https://github.com/openlab-aux/sphincter2-cad>
* code
  * sphincterd -> <https://github.com/openlab-aux/sphincterd>
  * sphincter2.0   -> <https://github.com/openlab-aux/sphincter2.0>
* pcb (symlink nach sphincter2.0 repo)

@waaaaargh @phil-underscore @michiwend 

Ach ja, @phil-underscore, magst du evtl. das ownership von der sphincter2.0 repo an openlab-aux übergeben? Du müsstest den fork halt vorher löschen (ich hab dich zur GH-Organisation eingeladen, solltest du also jetzt können).

Außerdem: Sind die OpenSCAD-Dateien im sphincter2.0-repo duplikate von <https://github.com/openlab-aux/sphincter2-cad>?

**Comment by sternenseemann** [comment]
ping @waaaaargh @phil-underscore @michiwend
