### ISSUE TITLE
Einkauf tätigen

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#226]
https://ola.pads.ccc.de/einkaufsliste-01

**Comment by Profpatsch** [comment]
Warum einfach schließen? Es ist nichts passiert.

**Comment by sternenseemann** [comment]
Ich habe das mit einem anderen Issue verbunden, das aktueller ist, wenn du aufgepasst hättest

**Comment by sternenseemann** [comment]
#230

**Comment by Profpatsch** [comment]
Dann gleich verlinken beim Schließen, man kann nicht den kompletten Überblick haben.

**Comment by sternenseemann** [comment]
Ja, hatte nicht bedacht, wie Github-Mailnotifications funktionieren, hast Recht.
