### ISSUE TITLE
Einkauf

### ISSUE THREAD

**Issue by verbosemode** [openlab-aux/orgafoo#230]
https://ola.pads.ccc.de/einkaufsliste-01

**Comment by sternenseemann** [comment]
Küchenrolle gibt es doch genug oder?

**Comment by sternenseemann** [comment]
Bitte einfach die Einkaufsliste abarbeiten: <https://ola.pads.ccc.de/einkaufsliste-01>

**Comment by verbosemode** [comment]
Ah ok. Küchenrolle hatte ich nur noch 1 entdeckt. Aber das kann man ja vor dem Einkauf nochmal verifizieren.

**Comment by sternenseemann** [comment]
Kann mich auch täuschen.

**Comment by Profpatsch** [comment]
Ich schließe das mal und pushe es in das Repo selbst.
