### ISSUE TITLE
Wandtablet ist verschwunden

### ISSUE THREAD

**Issue by sternenseemann** [openlab-aux/orgafoo#231]
Wer hat das Wandtablet verräumt oder mitgenommen? @phjlipp wollte es an der Wand befestigen, es ist aber nicht mehr zu finden.

Wer weiß, wo es ist, möge es doch bitte sagen.

**Comment by grindhold** [comment]
quo vadis, ola?

**Comment by sternenseemann** [comment]
Aktueller Status: @phjlipp hat das WandTablet durch ein anderes Tablet ersetzt.

Sehr unbefriedigende Situation, da da Tablet eine Leihgabe vom Falk war (ist?).

**Comment by sternenseemann** [comment]
@phjlipp wie ist es denn jetzt?

**Comment by phjlipp** [comment]
Das ursprüngliche Brett ist immernoch verschollen und wurde zwischenzeiltich durche eines vom @salomonderossi ersetzt. Mehr weiß ich aktuell nicht, der verbleib des alten Tablets ist unklar.

**Comment by phjlipp** [comment]
Das hat sich wohl inzwischen im Sand verlaufen. Schade, aber naja.
