### ISSUE TITLE
Webseite: Link zum Wik

### ISSUE THREAD

**Issue by cko** [openlab-aux/orgafoo#233]
Der Link zum Wiki auf https://openlab-augsburg.de/ verweist noch auf https://wiki.openlab-augsburg.de/openwiki:start vermutlich sollte es https://wiki.openlab-augsburg.de/ sein

Sehr cool übrigens, das ihr ein Haskell-basiertes Wiki verwendet!

**Comment by richi235** [comment]
Ja, wir haben ein paar überzeugte Haskell Evangelisten im Labor

**Comment by Profpatsch** [comment]
Habe es gefixt.

Gitit ist einfach überlegene Software. :)
Im Ernst, ich bin jedes mal wieder erstaunt, wie schnell das Ding ist.

**Comment by moba** [comment]
Bitte nicht die http-, sondern direkt die https-Variante verlinken -> fixed

**Comment by Profpatsch** [comment]
Oops, kommt davon, wenn man die schlechte Arbeit vom Vorgänger nicht richtig überprüft -.-
