### ISSUE TITLE
Website: "Wie funktioniert das OpenLab"-Wikilink tot

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#234]
Unter "Verein & Mitgliedschaft" auf der Website werden die Policies im [alten] Wiki verlinkt. Diese gibts wohl auf dem neuen Wiki noch gar nicht.

**Comment by Profpatsch** [comment]
Wir haben das Ziel, die alten Links zu redirecten. Sind nur noch nicht dazu gekommen. Blockt momentan auf den @waaaaargh.

**Comment by moba** [comment]
Naja in dem Fall gibts den Artikel halt nicht mehr, da gibts auch nix hinzuleiten :)

**Comment by sternenseemann** [comment]
Ja, den wollte ich ja noch migrieren, aber dann hat *hust* @Profpatsch *hust* das alte Wiki unerreichbar gemacht.

**Comment by sternenseemann** [comment]
Redirect geht jetzt, migriere den Content morgen.

**Comment by sternenseemann** [comment]
Erledigt.
