### ISSUE TITLE
Klopapier einkaufen -> Auf Lager 0%

### ISSUE THREAD

**Issue by verbosemode** [openlab-aux/orgafoo#235]
- Klopapier ist keins mehr da
- Küchenrollen sind auch keine mehr da

Bei der Beschaffung kann man evtl auch noch die Einkaufsliste vorher anschauen.

Relatiert zu issue https://github.com/openlab-aux/orgafoo/issues/230

Haben die Problematik leider erst nach 20 Uhr erkannt.

**Comment by sternenseemann** [comment]
Shit happens.
