### ISSUE TITLE
Events per SpaceAPI zugänglich machen

### ISSUE THREAD

**Issue by sternenseemann** [openlab-aux/orgafoo#236]
Für [spaceapi.ccc.de](https://spaceapi.ccc.de/) sollten wir unsere Veranstaltungen per SpaceAPI verteilen. Das Funktioniert so:

``` json
      "feeds": {
             "calendar": {
                    "type": "ical",
                    "url": "https://example.com/events.ics"
              }
      },
```

Fällt aus dem Kalender-Plug-In ics raus?

Außerdem können wir dann noch das Feld zur CCC-Zugehörigkeit hinzufügen:

``` json
         "ext_ccc": "family”,
```

ping @waaaaargh

**Comment by Profpatsch** [comment]
> Fällt aus dem Kalender-Plug-In ics raus?

hahahahahha … HAHAHAHAHAHAHAHAAAAAAHAHAHAHAHA

**Comment by moba** [comment]
https://openlab-augsburg.de/events.ics

**Comment by sternenseemann** [comment]
[siehe auch](https://lokal.ccc.de/spaceapi-ccc-de/)

**Comment by sternenseemann** [comment]
Müsste man da nicht einfach nur [spaceapi.json.data](https://github.com/openlab-aux/labapid/blob/master/spaceapi.json.data.example) anpassen? @waaaaargh

**Comment by Profpatsch** [comment]
Kann mir trotzdem nicht vorstellen, dass das ein valides ics ist, das auch nur halbwegs bugfrei läuft.

**Comment by moba** [comment]
Sag mal, Profpatsch, wie wärs mit mit konstruktiven Beiträgen? Was geht denn mit dir ab?!

**Comment by sternenseemann** [comment]
Wenn es halt inhaltlich korrekt wäre…

**Comment by moba** [comment]
http://severinghaus.org/projects/icv/?url=https%3A%2F%2Fwww.openlab-augsburg.de%2Fevents.ics Congratulations; your calendar validated!

https://openlab-augsburg.de/events.ics Success! No errors found. Warnings: Line length should not be longer than 75 characters

**Comment by Profpatsch** [comment]
> Was geht denn mit dir ab?!

kA, zu viel Kontakt mit dem Owncloud Kalenderplugin?

**Comment by sternenseemann** [comment]
Erledigt, siehe #239.

**Comment by Profpatsch** [comment]
*productiviting intensiefies*
