### ISSUE TITLE
Licht Bibliothek

### ISSUE THREAD

**Issue by devkral** [openlab-aux/orgafoo#237]
die Energiesparlampe in der Bibliothekecke ist nur ein dreckiger Hack (Energiesparlampe hat Anlaufzeit, daher blinkt sie nicht).
Vernünftige Lösung wäre sinnvoll (LED-Leiste, Umsetzung die mit $Glühbirne funktioniert).

**Comment by momo-aux** [comment]
Was ist das denn genau für eine Lampe?
Sind keine EVGs mehr da um die umzubauen?
Normalerweise kann man so Leuchtstoff gedöns mit nem EVG verheiraten, dann hat man nen Schnellstart ohne flackern.

**Comment by sternenseemann** [comment]
Ist das noch aktuell, Bibliothek ist mittlerweile ganz anders?

**Comment by robinkaranu** [comment]
Ja, Bibliothek gibts nicht mehr und Licht wurde mehrfach verändert. Ich würde es aktuell als "gemütlich und bunt" bezeichnen und hab keine Klagen gehört. Ich mach das mal zu.
