### ISSUE TITLE
Telefon (SIP) funzt ned

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#238]
An sich haben wir eine SIP-Telefonnummer und dank Privi ein SIP-Telefon. Nur irgendwie funktioniert das nicht. Müßte sich mal jemand anschauen. SIP-Accountdetails hat Hannes, das SIP-Telefon steht entweder noch irgendwo im Space (war mal im Küchenbereich auf dem Fensterbrett) oder Privi weiß wos ist.

**Comment by phjlipp** [comment]
Es gibt inzwischen unter einer neuen Nummer (steht auf der Webseite) ein FeTAp 881, das kann Telefon, rein sowie raus. Wenn das DECT da mit eingerichtet werden soll, einfach kurz bescheid geben.

**Comment by sternenseemann** [comment]
Könnten wir nicht beide Nummern aufschalten bei der FritzBox?

**Comment by phjlipp** [comment]
ja, das ist möglich
