### ISSUE TITLE
Defekte Links auf Bilder in der SpaceAPI

### ISSUE THREAD

**Issue by verbosemode** [openlab-aux/orgafoo#239]
Folgende Links in der Ausgabe der [SpaceAPI](https://api.openlab-augsburg.de/13) liefern einen 404er:

- "logo": "https://api.openlab-augsburg.de/static/logo_400px.png"
- "closed": "https://api.openlab-augsburg.de/static/closed.png"
- "open": "https://api.openlab-augsburg.de/static/open.png"

Dadurch bekommt man in der [Android MyHackerspace App](https://github.com/fixme-lausanne/MyHackerspace) direkt eine schöne Java Exception angezeigt, wenn man unseren Hackerspace aus der Liste auswählt ```¯\_(ツ)_/¯```

Vielleicht kann jemand mit Zugriff auf den Webserver die korrekten Pfade finden und in der API fixen.

KTHXBYE

**Comment by sternenseemann** [comment]
In dem Zuge könnte man auch den iCalendar-Feed hinzufügen:

    { …
      "feeds" : {
         …
         "calendar" : {
            "type" : "icalendar",
            "url:" : "https://openlab-augsburg.de/veranstaltungen/events.ics"
         },
         …
      },
    }

**Comment by sternenseemann** [comment]
Habe auf dem Webserver die `  spaceapi.json.data`   vom labapid aktualisiert und die nginx config angepasst, sodass die Grafiken wieder korrekt ausgeliefert werden. Zusätzlich liefert die SpaceAPI den RSS-Feed vom Block und den ICS-Feed vom Kalender korrekt valide nach der  v1.3 Spec aus.
