### ISSUE TITLE
Leaflet-Plugin lädt content von third party sites

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#240]
"Früher" war das mal so, dass wir keine externen Inhalte von fremden Seiten eingebettet haben. Das Leaflet-Plugin war auch entsprechend konfiguriert. Gerade ist mir aufgefallen, dass das wieder umgestellt wurde oder sich mit einem Update umgestellt hat.

In dem Zuge könnte man noch die Content-Security-Policy entsprechend setzen damit das nicht mehr vorkommt.

**Comment by Profpatsch** [comment]
Ich werde mich nicht drum kümmern, hab kein Bock auf WP.

**Comment by sternenseemann** [comment]
Kann ich mich drum kümmern, wenn ich die Anreise reinbaue.

**Comment by moba** [comment]
Dazu muß und sollte man nichts "in Wordpress" oder in irgendwelchen PHP-Sourcen ändern, das wäre bösartig gehacked und mit dem nächsten Update sowieso weg.

**Comment by sternenseemann** [comment]
Ich hatte auch eher vor, dass mit OpenLayers zu machen, weil in Leaflet muss man für GPX noch ein Plugin laden und somit vergrößert sich das „lade das nicht von einem CDN nach, bitte”-Problem.

**Comment by phjlipp** [comment]
Inwiefern ist das nun reparabel oder inwiefern ist das egal?

**Comment by moba** [comment]
Egal finde ich es nicht. Repariert gehört hier meiner Meinung nach:

- Content-Security-Policy anziehen
- Kram wieder wie vorher von lokal laden

**Comment by sternenseemann** [comment]
Ich plane weiterhin, das zu machen.

**Comment by robinkaranu** [comment]
Gibt es hier noch Handlungsbedarf? Aktuell sehe ich keinen externen content außer die tiles von OSM nachgeladen bei mir?

**Comment by derphjl** [comment]
Dieses Issue wurde im Sinn abgelöst durch #314
