### ISSUE TITLE
Stackenblocken alle 2-3 Tage, verschieben auf andere Tage

### ISSUE THREAD

**Issue by devkral** [openlab-aux/orgafoo#242]
jeder Tag nervt einfach. Und in paar Monaten wird es völlig ignoriert/deaktiviert weil es nervt.
Plus: es muss eine Möglichkeit geben, Tage auszunehmen, weil sonst Vorträge gestört werden.

**Comment by Profpatsch** [comment]
Bin ich stark dagegen. Es ist so sauber gerade *weil* wir jeden Tag Stackenblocken.

Tage ausnehmen: PR welcome. Das wird momentan mit einem [systemd-Timer](https://github.com/openlab-aux/vuizvui/blob/master/modules/user/openlab/stackenblocken.nix#L16) gemacht, der ein [bash-Skript](https://github.com/openlab-aux/vuizvui/blob/master/pkgs/openlab/stackenblocken/default.nix) triggert. Wenn jemand eine schöne Lösung für inhibit anbieten kann, gerne in [einem Issue](https://github.com/openlab-aux/vuizvui/issues) besprechen.

**Comment by momo-aux** [comment]
[Bash-Script](https://github.com/openlab-aux/vuizvui/blob/master/pkgs/openlab/stackenblocken/default.nix) erweitern, dass es den [Kalender](https://openlab-augsburg.de/veranstaltungen/) abruft und wenn ein Eintrag mit Tag #Vortrag oder irgendwas in der art  drin steht, wird nur dumrumgeleuchtet oder gar nichts gemacht.

**Comment by momo-aux** [comment]
Hab mal was [gebastelt](https://gist.github.com/momo-aux/0ad25379aaf398c9df1020cee77c0be5), bitte erweitern :-)

**Comment by Profpatsch** [comment]
Kann man machen, bin ich jetzt nicht so begeistert. Dann hängt das Stackenblocken plötzlich vom Kalender ab.

**Comment by Profpatsch** [comment]
Andererseits: YOLO

**Comment by devkral** [comment]
https://gist.github.com/devkral/aa2d6b2c34e58ef5aa40ea72a3cb30d7

**Comment by Profpatsch** [comment]
Find ich gut, werde ich heute Abend integrieren.
Sollte ich es vergessen, ping mich nochmal.

**Comment by Profpatsch** [comment]
Done.
