### ISSUE TITLE
Küche

### ISSUE THREAD

**Issue by derphjl** [openlab-aux/orgafoo#243]
Zur allgemeinen awareness wohl noch nicht geöffnet: 
Die Küche, wie sie jetzt steht, ist nicht fest installiert, aller schlodder läuft nach hinten, das ist so kein Dauerzustand. Es gilt, dass die gesamte Küche mal rausgenommen, dahinter saubergemacht und das ganze dann vernünftig hinmontiert werden muss. Zeitaufwand wäre wohl so ein langes Wochenende oder ne ganze Woche.

**Comment by robinkaranu** [comment]
Ich denke Großteile der Küche werden bald entsorgt. Was wir z.B. in das OpenLab 3 mitnehmen wollen, können wir in anderen Ticket in entsprechenden Milestones klären
