### ISSUE TITLE
Schneidplotter für unkundige Normalsterbliche im Wiki rudimentär dokumentieren

### ISSUE THREAD

**Issue by brantsch** [openlab-aux/orgafoo#244]
Seite wurde heute Abend angelegt. Ich bitte um Ergänzung.
https://wiki.openlab-augsburg.de/Schneidplotter

**Comment by robinkaranu** [comment]
Der Plotter lebt nicht mehr im Lab, entsprechend können wir dieses Issue denke ich schließen.
