### ISSUE TITLE
wiki reset passwort link karpot

### ISSUE THREAD

**Issue by momo-aux** [openlab-aux/orgafoo#248]
This link no good: 
http://s3mwj0l:5001/_doResetPassword?reset_code=kaffeeolafeekarpot0815&username=momoaux
So kommt er per post

Wenn mann ihn umbaut in 
http://wiki.openlab-augsburg.de/_doResetPassword?reset_code=kaffeeolafeekarpot0815&username=momoaux

tut er was er soll.

**Comment by Profpatsch** [comment]
OH LOL

Ich schau mal, was sich machen lässt.

**Comment by sternenseemann** [comment]
topkek

**Comment by Profpatsch** [comment]
Ich finde wohl so schnell keine Zeit dafür, @sternenseemann, wollen sie das übernehmen?

**Comment by sternenseemann** [comment]
Hat sich mittlerweile erledigt (sorry für die Mail momo).
