### ISSUE TITLE
Wiki XML feed kaputt

### ISSUE THREAD

**Issue by muesli** [openlab-aux/orgafoo#250]
Invalid XML.

**Comment by cko** [comment]
könntest du eine url dazu angeben?

**Comment by muesli** [comment]
https://wiki.openlab-augsburg.de/_feed/

**Comment by sternenseemann** [comment]
Ist von @Profpatsch ausgeschaltet (?) worden aus Gründen?

**Comment by Profpatsch** [comment]
> Ist von @Profpatsch ausgeschaltet (?) worden aus Gründen?

Nein, ist von mir angeschaltet worden aus Gründen und dann nie wieder angefasst; also kann es nur noch eine andere Person verändert haben @sternenseemann :p

**Comment by sternenseemann** [comment]
Also ich könnte mich daran erinnern!

**Comment by sternenseemann** [comment]
der global und die seitenspezifischen atom feeds sind wieder angeschaltet und produzieren [valide atom feeds](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwiki.openlab-augsburg.de%2F_feed%2F).

dazu habe ich in `gitit.config` gesetzt:

```ini
# feed anknipsen
use-feed: yes

# wichtig hier: https sonst assumed autodetection http und self reference is kaputt
base-url: https://wiki.openlab-augsburg.de

# ein bisschen über 2 monate sollte bei unserem aktivität in ordnung sein
base-url: https://wiki.openlab-augsburg.de
```

`feed-refresh-time` ist bei 5 minuten aktuell, also so lang wird der feed gecached bis er neu generiert wird. also sollte eine feed bee zb auch nur in dem rhythmus refreshen…

außerdem habe ich die wichtigen werte in der default config, die wir ausliefern, [angepasst](https://github.com/openlab-aux/gitit/commit/4efb5f5271882c2ad65755820fabf5743c8d156d), aber gitit nicht von diesem commit aus neu gebaut.
