### ISSUE TITLE
Raumstatus in IRC-Topic statt auf .status

### ISSUE THREAD

**Issue by phjlipp** [openlab-aux/orgafoo#251]
Aktuell: 
phj | .status                                            
  -- | Hinweis(labbee): +++ Lab-Status: aufgesperrt +++   
  -- | Hinweis(labbee): +++ Netzwerk-Status: 5 Nutzer +++ 
   * | Dummrumleuchte ist bereit seit 362794s @ 12.264V   

Besser wäre es, wenn der Raumstatus als erstes item im topic stünde, vgl.
"club member | ASM17 - https://asm17.muc.ccc.de | Heute: ab 18:00 Grillen"

und .status dann nur 
-- | Hinweis(labbee): +++ Netzwerk-Status: 5 Nutzer +++ 
 * | Dummrumleuchte ist bereit seit 362794s @ 12.264V    
zurückgäbe

**Comment by grindhold** [comment]
war da nicht mal die ueberlegung, dass man das nicht gleich sofort nach ganz freenode publizieren moechte? sondern auf die leute beschraenken will, die wissen, dass es diesen command gibt?

**Comment by Profpatsch** [comment]
Bei Topicänderungen hat man mindestens den gleichen Overhead im IRC, zusätzlich muss man noch irgendwie den Status erkennen und anpassen, ohne manuell gesetzte Topics zu überschreiben.
