### ISSUE TITLE
RFID-Leser abgerissen

### ISSUE THREAD

**Issue by phjlipp** [openlab-aux/orgafoo#254]
Die Jugendlichen, die gestern nach dem Modular noch bei uns vorbeigestrahlt sind, haben sich größtenteils ganz okay verhlten (sie haben noch auf der terasse gechillt), aber haben den RFID-Leser abgerissen. Was nun? Wo gibt es Ersatz? Würde montieren.

**Comment by pRiVi** [comment]
Das Zeug, dass du neulich ohne Haufenprozess wegschmeißen wolltest, und nur durch den Flypps gerettet wurde, ist alles was zur Reparatur notwendig ist.

Ich kümmere mich die Tage darum.

**Comment by phjlipp** [comment]
Ich habe es am selben abend wieder angelötet, es funktioniert wieder. Da wir keinen vernünftigen Kleber mehr haben, habe ich es noch mit einer Schraube fixiert. Nicht schön, aber selten.




@pRiVi Das ist so nicht richtig, ich habe den flypps explizit gefragt, was damit ist und was man damit tun soll. Er sagte, er gibt es dir. So wie das da steht ist das eine ziemlich offensive Behauptung!

**Comment by pRiVi** [comment]
In dem Fall möchte ich mich für die Behauptung entschuldigen, dann habe ich das wohl falsch verstanden.
