### ISSUE TITLE
Terassenupgrades

### ISSUE THREAD

**Issue by phjlipp** [openlab-aux/orgafoo#255]
Nach dem Abend, wo die Jugendlichen da waren, ist nun die Tresse etwas dreckig, den Tisch müsste man mal putzen etc.

Weiter hätte ich in nächster Zeit mal vor, die Sofas dem Sperrmüll zuzuführen und dafür ein paar andere "zu verschenken" auf Kleinanzeigen zu holen. Bei dem Zustand wird das wirklich mal Zeit (was eigentlich auch für die Sofas innen gilt)

**Comment by Profpatsch** [comment]
> Tisch müsste man mal putzen etc.

Tisch wurde von @waaaaargh geputzt.
