### ISSUE TITLE
Tape anschaffen

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#256]
Die Tapes vom letzten Großeinkauf sind jetzt langsam komplett aufgebraucht. afaik war das eine billige Ebay-Ersteigerung damals, das hat recht lange gehalten.

Also: https://www.ebay.de/sch/i.html?_from=R40&_trksid=p2050601.m570.l1313.TR0.TRC0.H0.Xthinkpad+mini+dock+plus+3.TRS0&_nkw=tape&_sacat=0

**Comment by phjlipp** [comment]
10:45:15 gamambel | phj: 24 rollen panzertape unterwegs zum lab, 44,99 inkl versand

**Comment by moba** [comment]
( http://www.ebay.de/itm/172650861332 )
