### ISSUE TITLE
Interniet

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#258]
```
curl: (7) Failed to connect to haku.profpatsch.de port 443: Connection timed out\n
```

```
---
version: 0.2
date: 2017-07-11 00:15:46.086933
ping-v4: true
ping-v6: false
dns: true
download_speed: 4076239
---
version: 0.2
date: 2017-07-11 00:30:34.468096
ping-v4: false
ping-v6: false
dns: false
download_speed: 0
```

**Comment by sternenseemann** [comment]
Wie @moba anmerkte, ist es auf jeden Fall sinnvoll, eine schrittweise Anleitung nach dem Motto "WAS TUE ICH WENN INTERNET DOWN. SCHRITT EINS. SCHRTIT ZWEI. SCHRITT DREI" zu schreiben.

**Comment by muesli** [comment]
(SCNR)

**Comment by Profpatsch** [comment]
> Wie @moba anmerkte, ist es auf jeden Fall sinnvoll, eine schrittweise Anleitung nach dem Motto „WAS TUE ICH WENN INTERNET DOWN. SCHRITT EINS. SCHRTIT ZWEI. SCHRITT DREI“ zu schreiben.

Mach halt’n Issue auf
