### ISSUE TITLE
Klinke-Kabel

### ISSUE THREAD

**Issue by phjlipp** [openlab-aux/orgafoo#262]
Durch wahrscheinlich machanisch starke belastung oder wildes umstecken ist das Klinke-Kabel:
1. Entgegen der Dokumentation verbunden worden
2. Mechanisch an beiden Kanälen entweder beschädigt oder zerstört. 

Ich werde die Tage, wahrscheinlich heute, mal sehen, was man da so richten kann und bitte in Zukunft davon abzusehen, Kabel zu zerstören, die sinnvoll sind. Danke :)

**Comment by Profpatsch** [comment]
Wenn man es wie gehabt wieder an einen Kabelbinder befestigt vermeidet man direkte Krafteinwirkung auf die Steckerverbindung am Mischpult.

**Comment by phjlipp** [comment]
Ein neues Kabel erschien :)
