### ISSUE TITLE
Zu viele Cincheingänge

### ISSUE THREAD

**Issue by sternenseemann** [openlab-aux/orgafoo#263]
Da wir jetzt auch Schallplatten haben will man eigentlich folgende Eingänge mit dem Mischpult abfrühstücken:

- Schallplattenspieler
- Tonbandgerät
- Klinke
- Pulseaudio Sink

Aktuell gibt es zwei belegte Eingänge am Mischpult:

- Pulseaudio
- Cinch Merger für zwei Anschlüsse

Insofern müssten wir entweder noch einen Merger besorgen oder irgendwie die wei anderen Kanäle belegen, die haben aber nur XLR (iirc) ist also eher stressig.

**Comment by phjlipp** [comment]
Die 2 XLR-Kanäle (1 & 2) sind Mono-Kanäle für Mikros. Aber ja, werde Doku überarbeiten. Erst, wenn ich wieder in Augsburg bin (5.9.) :)

**Comment by sternenseemann** [comment]
Naja, das problem ist, dass permanent Leute Dinge aus-/umstecken müssen vor allem.

**Comment by phjlipp** [comment]
Müssen sie nicht, tun sie trotzdem. Denkst du wirklich, es würde jemand in die Doku schauen, auch wenn es sie gäbe :>

Auch im aktuellen Status ist eingangsweise alles so zussammen gesteckt, dass niemand stecken muss. Aber die Leute machen es unvermeidlich trotzdem :>
