### ISSUE TITLE
Laminierte Schilder vorne an den Pfosten und hinten an den Zaun

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#266]
Wir hatten eine Weile mal laminierte Schilder mit OpenLab-Logo und Pfeil, damit man uns auch finden kann. Die sind witterungsbedingt verschwunden.

Vermutlich wärs auch gut am Klingelschild vorne einen kleinen Hinweis anzubringen.

**Comment by moba** [comment]
Push? Gibts niemanden mit Zugriff auf ein Laminiergerät? Zumindest hinten am Zaun wäre echt gut zu haben, gefühlt ständig finden uns Leute nicht, von Lieferdiensten über Gäste usw...

**Comment by momo-aux** [comment]
Ich hab, A4 kann ich selber, größer kann ich machen lassen.
Her mit der PDF Vorlage und ich kümmer mich um den Rest.

**Comment by momo-aux** [comment]
PDF? Wo? Laminierer ist mittlerweile warm ;-)

**Comment by moba** [comment]
Der phj hat jetzt eins an die Treppe gemacht (yay!). Ich fands am Zaun besser und sichtbarer, insbesondere wenn da parkende Autos davor stehen. Das heißt es gibt noch die Chance das mit einem weiteren Schild dann zum Schilderwald zu machen ;-)

https://transfer.sh/ekGjp/openlab-pfeil-wegbeschreibung.pdf hatte ich mal schnell zusammengekloppt für das alte Schild am Zaun.
