### ISSUE TITLE
Lötstation macht Probleme...

### ISSUE THREAD

**Issue by Wuerfel21** [openlab-aux/orgafoo#269]
Vielleicht verstehe ich das Ding einfach nicht, aber die gegenwärtig aufgebaute Lötstation hat eigenartige Probleme (neue Spitze benötigt?):

- Spitze wird ganz vorne nicht wirklich heiß
- Funktioniert eig. nur, wenn die gemessene temperatur niedriger als die eingestellte ist, d.h. immer wieder abkühlen und aufheizen erforderlich

**Comment by robinkaranu** [comment]
Ich konnte das Problem mit keiner der beiden aktuellen Lötstationen bei normalen THT-Boards nachvollziehen. Ist das noch aktuell?
