### ISSUE TITLE
Kühlschranklicht kaputt

### ISSUE THREAD

**Issue by sternenseemann** [openlab-aux/orgafoo#276]
Wenn man den Kühlschrank aufmacht, leuchtet die Lampe nicht. Wie die Situation bei geschlossener Tür ist, weiß ich nicht.

**Comment by robinkaranu** [comment]
@derphjl hat es wieder in Betrieb genommen. Was war zu tun?

**Comment by derphjl** [comment]
Der Kühlschrank braucht so eine max10W 12V Halogen mit so einer rechteckigen Plastik-Basis mit Nase. Ich habe jetzt eine 5W5 beim Einbauversuch zerstärt und eine weitere, sehr ähnliche, erfolgreich eingebaut. Kein Halogen, aber 5W < 10W also wenn sie nicht physikalisch rausfällt, kann man das so lassen. Besser wäre sicher was in LED, was auch mehr Lichtausbeute gibt - die 5W Gluhbirne ist ein bisschen... dimm. Aber für den Moment kann man wieder die Flaschen sehen, also passt schon.

**Comment by robinkaranu** [comment]
Die Frage ob sie durchleuchtet bleibt zunächst ungeklärt.

**Comment by derphjl** [comment]
> Die Frage ob sie durchleuchtet bleibt zunächst ungeklärt.

Naja. Die drück-Bewegung, die die schließende Tür auf die Lampenhalterung und Türschließerkennung ausübt, lässt sich auch bei offener Tür simulieren: Drückt man auf diese Einheit, geht die Lampe aus und der Ventilator an.

Ob das auch der Realtät entspricht und die Tür tatsächlich eine entprechende Bewegung dieser Einheit bewirkt, bleibt offen. Sicher ist allerdings, dass die Lampe, wenn sie an ist, etwa 5W an Wärmeenergie abgibt. Bliebe die Lampe also an, könnte man das sicher an einem erhöhten Stromverbrauch ablesen. 

Hier könnte man per Testaufbau mit Beobachtung des Stromverbrauchs bei eingebauter oder ausgebauter Lampe weitere Erkentnisse erlangen. Die Beleuchtung, auch für Testzwecke, außer Betrieb zu nehmen hätte allerdings eine katastrophale Auswirkung auf die User-Experience und kann deshalb nicht in unserem Interesse sein.

Letztendlich bleibt die Frage also tatsächlich ungeklärt.
