### ISSUE TITLE
Mietvertrag für die Bäckergasse 32 reviewen und unterschreiben

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#279]

**Comment by robinkaranu** [comment]
Freitag nachmittag

**Comment by robinkaranu** [comment]
Ein Mietvertrag liegt vor, kleine Details möchten wir noch gemeinsam mit dem Vermieter besprechen und evtl. ändern, bevor wir unterzeichnen.

**Comment by derphjl** [comment]
Der Mietvertrag ist unterschrieben und liegt in Kopie beim Vorstand. Die Wichtigsten Punkte wurden auch auf der MV 2022 erwähnt: [Hier das Protokoll](https://github.com/openlab-aux/orgafoo/blob/master/Protokolle-Mitgliederversammlung/MV2022Protokoll.pdf)

Die Wichtigsten Punke dabei:
- Die Mindestvertragslaufzeit von 2 Jahren wurde auf unseren Wunsch entfernt. Wir wollen natürlich trotzdem mehr als nur 2 Jahre dort bleiben :>
- Die Staffel aus der ursprünglichen Version des Mietvertrags wurde entfernt.
- Der Mietvertrag sieht eine Kaltmiete von 1200€ plus einer Nebenkostenpauschalzahlung von 300€ vor uns ist somit in summe 100€ teurer als der alte Vertrag (da waren es pauschal 1400€ warm für die gesamte Mietzeit). Die Pauschale der Nebenkosten kann sich verbrauchsentsprechend von Jahr zu Jahr ändern.
- Der Vertrag ist geschlossen zwischen dem Vermieter und dem Verein. Zusätzlich stehen die Vorstände einzeln und persönlich im Mietvertrag, ein Vorstandswechsel geht in Zukunft einher mit einem entsprechenden Anhang an den Mietvertrag.
