### ISSUE TITLE
Räume in der Bäckergasse vermessen und Grundrissplan anfertigen

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#280]
Eventuell auch Günther fragen, ob er schon einen aktuellen hat.

**Comment by derphjl** [comment]
Ich hab den Schlüssel geholt und auch schon zwei lange Abende mit vermessen verbracht, es gab weiterhin täglich Besichtigungen verschiedenster Mitglieder

Die Pläne sind in vorläufiger Version zur Hälfte fertig, einige Stunden Arbeit werden da noch rein fließen müssen, bis sie präsentierbar sind.

**Comment by derphjl** [comment]
Ich kann nun alle auf meinen satz an Plänen loslassen zum ideen einzeichnen oder was auch immer :D https://github.com/openlab-aux/orgafoo/tree/master/Skizze-Pla%CC%88ne-Ba%CC%88ckergasse

**Comment by derphjl** [comment]
Ideen zur Raumaufteilung finden entsprechend in #281 statt. Closing.
