### ISSUE TITLE
Initiale Raumaufteilung

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#281]
Es würde Reibungen minimieren, wenn wir vorab einen Konsens finden können, welche Räume wofür genutzt werden sollen. Das ganze wird sich bestimmt über die Jahre organisch entwickeln.

Welche Funktionen brauchen wir? Welche Räume haben besondere Eigenschaften (Lärmschutz, privater/öffentlicher, ..)? Welche Räume ergeben sich daraus? Wie teilen wir sie auf? Siehe auch #280 

Ich bin versucht das Beispiel aus Uwe Lübermanns Workshops zu verlinken :D

**Comment by derphjl** [comment]
Die Aufteilung der Räume und grobe Einrichtungsideen lassen sich gut angehen, wenn der Plan aus #280 fertig ist

**Comment by derphjl** [comment]
Ich kann nun alle auf meinen satz an Plänen loslassen zum ideen einzeichnen oder was auch immer :D https://github.com/openlab-aux/orgafoo/tree/master/Skizze-Pla%CC%88ne-Ba%CC%88ckergasse

**Comment by derphjl** [comment]
Ich habe die Pläne um eine meiner Aufteilungsideen und einen Satz an vermessen und skalieren Möbeln ergänzt, sodass jeder selbst ein paar Möbel durch die neuen Räume schieben kann, ganz virtuell.

**Comment by robinkaranu** [comment]
Meine Wahrnehmung aus der Praxis vor Ort inzwischen:
Hauptraum/Saal: Events, 3D-Drucker (funktionsfähige Geräte), Beamer, Audioanlage Schaufensterkram
Sofazimmer: Abseits arbeiten, lernen, Sofas, Arbeitsplätze, TV für Code-Sharing und Filmabend
E-Labor: Fräse + E-Labor
Keller: Lager + Infrastruktur (Wasch + Spülmaschine, ...)
