### ISSUE TITLE
Internet in der Bäckergasse

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#283]
- Vodafone Vertrag umgezogen (es reicht wohl technisch meistens, es anzustecken, falls eine Kabel-Dose gelegt wurde)
  - TV-Dose ist an der Wand zum Hof, Rechts unterm Fenster. Zum "Patchraum" müsste 1 Loch durch Trockenbau und Kabelkanal o.Ä. verlegt werden. ~30€, 2 Stunden Arbeit?
  - oder alternativ: Gekündigt/Anderen Vertrag. VDSL wäre verfügbar
- Luke umgezogen
- APs umgezogen (Braucht es eine neue, bessere WiFi-Lösung?)
- ...?

**Comment by robinkaranu** [comment]
Funzt provisorisch

**Comment by derphjl** [comment]
Ein Kabel ist bestellt, das von Kabeldose bis ins Rack reicht. So können allle Komponenten im Rack untergebracht werden, mit USV und so. 
Das kommt heute an und wir können es im Laufe des Tages oder morgen installieren. Einen Kabelkanal braucht es noch, um das ganze schön kabelzuführen.
