### ISSUE TITLE
Neue elektronische Zugangskontrolle

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#284]
- Der vorhandene Buzzer-Taster für die (vordere) Haustür darf "angezapft" werden
  - Könnte man z.B. bei offenem Lab direkt an die Klingel koppeln
- "Richtiges" abschließen der eigentlichen Lab-Tür in bekannte sphincter-Manier vermutlich weiter nötig
- HTTP-API nicht brechen
- Bestehende RFID-Datenbank mitnehmen
- ...?

**Comment by robinkaranu** [comment]
#225 :)

**Comment by robinkaranu** [comment]
Es gibt doch einen Buzzer für die "Wohnungstür", allerdings wurde dieser eventuell mal rückgebaut. Müssen wir wohl mal aufmachen um es weiter nachvollziehen zu können.

**Comment by robinkaranu** [comment]
@derphjl hat dieses Thema in die Hand genommen und auch einen Kanal namens "Airlock" im Mattermost dafür aufgemacht.

**Comment by derphjl** [comment]
Unter dem Projektnamen "Airlock" hab ich einen Mattermost-Kanal und eine Wiki-Seite angelegt, in der der Projektfortschritt festgehalten werden kann und über die Entwicklung kommuniziert wird:
https://wiki.openlab-augsburg.de/AirLock
