### ISSUE TITLE
Parkplatzreservierung für Umzug

### ISSUE THREAD

**Issue by Joeend** [openlab-aux/orgafoo#287]
## Für die Tage, an denen Umzug mit PKW/LKW geplant ist, kann man sich einen Parkplatz vor unserem neuen Domizil reservieren lassen. Guckst Du hier:
https://www.augsburg.de/buergerservice-rathaus/buergerservice/dienste-a-z/aemterweise/leistungen-tiefbauamt/umzuege-ausnahmegenehmigung/
- D.h. das kostet a bisl was und muss mindestens 14 Tage vorher erfolgen. Unbedingt machen, sonst wird es ätzend mit Schlepperei und weiten Wegen. 
- Wir müssen auch die Umzugstage zumindest für die großen Sachen fixieren. 
- Wenn die Tage feststehen, kann ich das übernehmen

**Comment by derphjl** [comment]
Wie in #288 erwähnt könnte Karfreitag, der 15.4.22 ein signifikanter Umzugstag werden. Inwiefern eine Extra Parkgenehmigung von Bedarf ist, weiß ich nicht.

**Comment by Joeend** [comment]
Für den 15. 4 können wir die 14 Tage Voranmeldung nicht einhalten. 
Wenn am Plenum 7.4. definitiv ist, dass der Mietvertrag unterzeichnet ist, könnte ich  z.B. für Samstag 23.4 und/oder Samstag 30.4. absperren lassen.

**Comment by derphjl** [comment]
Okay, ich habe nun auch zusätzlich für Samstag 23.04. reserviert. Gleiche Konditionen.

**Comment by derphjl** [comment]
Unabhängig von der Sperrung würde ich aber am 15. erstmal festhalten. Aber Mal sehen, was passiert.

**Comment by Joeend** [comment]
Der Antrag für die Reservierung des Parkraums vor Bäckergasse 32 für das Fahrzeug A CS 349 bei der Stadt ist gestellt.
Ich muss und kann noch eine Skizze mit der Straßensituation, d.h. mit den dort vorhandenen Verkehrszeichen, Parkmaßen und Durchfahrtsmaßen nachreichen. Die erstelle ich übers Wochenende.
[20220408328460252806_moebeltransport_ausnahmegenehmigung(1).pdf](https://github.com/openlab-aux/orgafoo/files/8449480/20220408328460252806_moebeltransport_ausnahmegenehmigung.1.pdf)

**Comment by KingBBQ** [comment]
Schilder stehen.
