### ISSUE TITLE
Umzugstage festlegen

### ISSUE THREAD

**Issue by Joeend** [openlab-aux/orgafoo#289]
- Machen wir große Hau-Ruck-Aktion(en) mit viel Man- und Woman-Power?
-- wenn ja, an welchen Tagen?
- Ziehen wir häppchenweise um - einzelene Mitglieder*Innen transportieren einzelne Sache an Tagen wie sie möchten?
-- wenn ja, wer transportiert was?

**Comment by robinkaranu** [comment]
Ich vermute fast, es wird auf eine Mischung aus beiden Varianten rauslaufen. Ich glaube, das ist ein Thema, das wir im nächsten Plenum dazu gut besprechen könnten.

**Comment by KingBBQ** [comment]
WE 23. / 24. April angedacht.

**Comment by derphjl** [comment]
Erste Dinge am Karfreitag 15.3. mit Carsharing Transporter. 

Weitere Fahrt am 23.4., inklusive extra reserviertem Parkplatz (entsprechende issue threads)

Dazwischen einzelne Fahrten von einzelnen Leuten für einzelne Kleinteile.

**Comment by robinkaranu** [comment]
Sollen wir noch einen dritten "großen Umzugstag" ansetzen? Oder reichen die beiden  zusammen mit ein paar privaten PKW-Fahrten? Ich war heute im alten Lab und kann das noch nicht so wirklich beurteilen. Vermutlich werden wir aber einige Entsorgungsfahrten brauchen. Für die erste gibt es schon #297, sollen wir das vielleicht in der nächsten Woche machen?

**Comment by robinkaranu** [comment]
Das alte Lab ist leer, morgen nachmittag ist die Übergabe anvisiert. Geil ey.
