### ISSUE TITLE
Fairteiler-Team informieren

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#290]
- Wir sollten bald den Menschen vom Fairteiler bescheid geben. 
- Sind sie interessiert an der neuen Location einen neuen Fairteiler zu betreiben? 
- Wäre das Studio unter uns vielleicht bereit, den bestehenden Fairteiler zu übernehmen? 
- ...?

**Comment by KingBBQ** [comment]
mach ich...

**Comment by robinkaranu** [comment]
Cool, hast du schon? Weeiil: Ich hab neulich schon einer "Auffüllerin" Bescheid gegeben, dass das Ende April offizielle vorbei ist. Auch vor ihr philosophiert, ob man mal im Studio unten fragen sollte. Erzählt dass wir wohl in die Bäckergasse gehen (falls sie dort Interesse und wir Möglichkeiten haben). Sie gibt das ihrem Kumpel weiter, der "voll im Food-Sharing-Game ist". Das hätte ich wohl auch ähnlich in die Mail gepackt :)

**Comment by KingBBQ** [comment]
Habe Bescheid gegeben. Müssen ja nix machen, Schrank ist ja unser.

**Comment by KingBBQ** [comment]
Nach Rücksprache mit dem Vermieter können wir das im neuen lab leider nicht weiter führen.
