### ISSUE TITLE
Sperrmüllabholung bestellen

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#291]
@derphjl hat schon recherchiert: Es ist wahrscheinlich, dass wir mit dem Abholungstermin in den Mai rutschen.. 
- Evtl. mal bei der AWS anrufen, ansonsten selbst wegfahren? 
- Oder für ein paar Tage an der Straße stehen lassen?

**Comment by derphjl** [comment]
Selbst weg fahren, wenn es gut strukturiert ist, ist gar kein Problem. Es gilt, die Öffnungszeiten der Wertstoffhöfe und die Sortierungskriterien zu beachten. 

Für den Transport sind Carsharing-Transporter unter der Woche relativ spontan bzw. am Samstag mit ca. 2 Wochen Vorlauf zu besorgen.

**Comment by KingBBQ** [comment]
Hab schon öfter Zeug in den Holzweg gefahren. Das geht super einfach und unkompliziert. Die nehmen auch wirklich alles (bis her zumindest)

**Comment by robinkaranu** [comment]
Es ist Quatsch, es abholen zu lassen. Haben wir auch im Plenum heute besprochen
