### ISSUE TITLE
Umzugskartons aquirieren

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#292]
Wir brauchen einiges an Umzugskartons für das lose Zeug.

Erste Schätzung zwischen 20 und 50.

Die Küche braucht ~4–6 Kartons.

Die Werkstatt braucht ?? Kartons.

Die E-Ecke braucht ?? Kartons.

Das Chemielabor braucht ?? Kartons.

Die Bücher & Spieleecke braucht ?? Kartons.

Das Bad braucht ~3 Kartons.

Das lose Zeug im Regal braucht ?? Kartons.

**Comment by derphjl** [comment]
Ich fahr später heute beim Baumarkt vorbei und kaufe ein paar. Dann sehen wir, wie weit die langen. Bedenkt auch, dass man Zeug wegwerfen kann :)

**Comment by derphjl** [comment]
Gerri hat welche vorbei gebracht, deswegen habe ich vorerst keine gekauft.

**Comment by momo-aux** [comment]
Habe 8 Stück, bringe ich schnellstmöglich ins Lab

**Comment by derphjl** [comment]
Die Menge an Umzugskartons ist wahrscheinlich kein Thema mehr, die aller meisten Dinge, die kartonfähig sind, sind schon umgzogen. Zu #295 passiert am ehesten noch Transport von großen Dingen, die nicht kartonisiert werden.
