### ISSUE TITLE
Getränkeautomat transportieren

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#293]
Die Treppe runter, der Rest wird leicht.

**Comment by KingBBQ** [comment]
Der muss auch noch repariert werden :-/

**Comment by robinkaranu** [comment]
Das ist für einen Kältetechniker aber vermutlich kein großes Problem. Ansonsten ist er ganz gut in Schuss, höchstens mal reinigungsbedürftig. :)

**Comment by derphjl** [comment]
Zu dem Thema ein paar Erfahrungswerte: Der Transport ist liegend auf einem konventionellen 750kg Anhänger passiert, das ist kein Problem (wobei dieses Ding super schwer ist. Garantiert das schwerste Einzelteil im Lab. Ich schätze Mal... 300kg? Schwer jedenfalls)

Aus dem Hänger aufstellen und Verfahren ist mit entsprechend Hunden, Hebeln, etc. Ganz okay möglich. 

Die Metalltreppe hoch ging es auf der Seite liegend auf bauplatten und mit Seilzug, das war eine ganz schön aufwändige Geschichte. Aber wahrscheinlich wird es auch wieder auf so eine liegende Geschichte mit Seilzug hinauslaufen. Wir brauchen einen guten, stabilen Seilzug!

**Comment by treilik** [comment]
Da kann ich ggf. helfen.
Entsprechende seile und karabiner hab ich.
Allerdings nicht diese Woche.

**Comment by derphjl** [comment]
Ich hab (zusammen mit @ma-hartma @robinkaranu ) die Tür abgenommen, anders als beim letzten Mal. Ich hab alle Einzelteile rausgenommen. Das Ding könnte jetzt plausibel mit ein paar Leuten und Sackkarre die Treppe runter schaffen. Müssen wir Mal ausprobieren. 

Die Tür wiegt jedenfalls alleine schon ne Menge.

**Comment by robinkaranu** [comment]
Morgen im Rahmen der zweiten Transportaktion soll es passieren. @momo-aux bringt den Treppensteiger mit, @derphjl hat den Transporter gemietet.

**Comment by robinkaranu** [comment]
Er ist im neuen Lab. Jetzt zusammenbauen und Kühlung reparieren.
