### ISSUE TITLE
Transporterfahrt 15.04.

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#294]

**Comment by derphjl** [comment]
Carsharing-Transporter A CS 386 am 15.3. vom 10:00 Uhr bis 21:00 Uhr 

Im alten Lab Hof wird alles ganz stressfrei, denke ich.

Im neuen Lab gelten wegen Karfreitag die Parkscheinregeln nicht, die Anwohnerausweisregeln auch nicht. Das bedeutet, die Straße könnte voll mit Dauerparkern stehen? Vielleicht will jemand mit A-Ausweis (gibt's da jemand?) nen Parkplatz saven? Sperren lassen konnten wir wegen der geringen Vorlaufzeit leider keinen.

**Comment by robinkaranu** [comment]
@derphjl holt den Transporter, Ich pack mit an. Wer packt noch mit an? Freitag, 15.4 ab ca. 10:30 am Lab.

**Comment by treilik** [comment]
bin wohl leider nicht in aux

**Comment by Profpatsch** [comment]
Ich werde kommen, ich kann noch nicht genau sagen, ab wann, aber so früh wie möglich.

**Comment by robinkaranu** [comment]
War ein voller Erfolg, wir haben locker 50% der Sachen die rüber müssen rüber gefahren! Danke an die vielen Helfer!
