### ISSUE TITLE
Erste Entsorgungsfahrt organisieren (Wertstoffhof-Öffnungszeiten und Carsharing-Transporter)

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#297]
> Hab schon öfter Zeug in den Holzweg gefahren. Das geht super einfach und unkompliziert. Die nehmen auch wirklich alles (bis her zumindest)

_Originally posted by @KingBBQ in https://github.com/openlab-aux/orgafoo/issues/291#issuecomment-1092017058_

Am unteren Talweg nehmen Sie auch alles (außer Bauschutt und sowas) und sind freundlich. @derphjl meinte, unter der Woche bekommt man die Carsharing Sprinter mit wenigen Tagen vorlauf, am Samstag mit 2-3 Wochen.

Da es mit dem Sperrmülltermin zu knapp wird, koordinieren wir also $n Entsorgungsfahrten. :)

**Comment by Joeend** [comment]
Öffnungszeiten Wertstoff- & Servicepunkt Unterer-Talweg und Holzweg (sind gleich!)

Di. 8.00 - 12.00 Uhr
Mi. 8.00 - 12.00 und 13.00 - 15.00 Uhr
Do. 8.00 - 12.00 und 13.00 - 18.00 Uhr
Fr. 8.00 - 12.00 und 13.00 - 15.00 Uhr
**Sa. 8.00 - 12.00 und 13.00 - 15.00 Uhr**

**Comment by derphjl** [comment]
Am großen Umzugstag, dem 23., wurde auch eine Fuhre Holz weg gefahren. 
Es schient nicht in der Kapazität des Umzugs gelungen zu sein, sinnvoll zwischen Müll und nicht-Müll zu sortieren. 
Viel mehr wurde alles mit umgezogen. 
Das ist nicht weiter Schlimm, die Sortierarbeit bleibt halt einfach bestehen.

Eine gewisse Menge müll hat es jedoch schon noch in die Ecke geschafft, die muss noch weg. Ich habe ein kleines Auto und versuche Donnerstag und Samstag dafür zu nutzen. Mal sehen, wie weit ich komme und was noch da steht.

**Comment by robinkaranu** [comment]
Heute passiert, das alte Lab ist leer.
