### ISSUE TITLE
Mitgliedsantrag - digital.

### ISSUE THREAD

**Issue by KingBBQ** [openlab-aux/orgafoo#298]
Ich denke wir sollten den als Formular auf der Webseite haben. Ist einfacher und wir können ihn ja dann ausdrucken wenn wir es anlegen wollen.

**Comment by derphjl** [comment]
Das Formular zum Mietgleidsantrag muss sowieso neu, weil neues Design (und man kann es ja gleich überarbeiten). Da ich das mit dem Design eingebrockt habe, werde ich nicht drumrumkommen, das auch hier zu übernehmen. 

Da so ein Mitgleidsantrag aber eh am besten mit Unterschrift und somit auf papier passiert, ist ein PDF mit forms wunderbar ausreichen. 

Wie gesagt, sobald ich dazu komme, kümmere ich mich drum.

Eine total digitale Lösung mit irgendwelchen google forms oder sowas steht ja meiner meinung nach eh nicht zur debatte, das wäre ja datenschutzmäßig eine katastrophe.

**Comment by KingBBQ** [comment]
Ich denke eine digitale Lösung per Formular - auf unserer Webseite, nicht in GDocs oder so! - wäre schon ausreichend. Alternativ Formular in unserem (selbstgehosteten) Nextcloud.
Aber nur Papier geht auch.

**Comment by robinkaranu** [comment]
Wäre also ein PDF, das aus einem Web-Formular generiert wird, ohne dass wir die Daten speichern, gut? Geht es (rechtlich) nicht ohne Unterschrift?

**Comment by derphjl** [comment]
Ein SEPA Lastschriftmandat braucht man physikalisch vorliegend mit Unterschrift. Die Außnahmen gibt es hier nur, wenn man sehr absurden digitalen Dokumentenverwaltungsvorgaben folgt, wenn ich das richtig verstehe. 

Es bleibt also mindestens wegen dem SEPA besser, ein Papier zu haben, mit einer bis zwei physikalischen Unterschriften. 

Form Fields, damit man es am computer füllen und dann drucken kann, hat ja selbst der alte Antrag schon seit Beginn. So auch der neue, an dem ich gerade arbeite.

**Comment by derphjl** [comment]
Der Mitgliedsantrag ist als PDF mit Form Fields, also digital ausfüllbar, [hier zu finden](https://github.com/openlab-aux/orgafoo/blob/master/vorlagen/mitgliedsantrag.pdf)

Wegen den aufgeführten Problemen (bei SEPA besser eine physikalische Unterschrift haben) und weil wir den Mitgliederbestand so oder so auch als Papier führen, ist eine ausschließlich digitale Lösung nicht sinnvoll.
