### ISSUE TITLE
Energiezähler vor boot ablesen

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#301]
Damit wir genau wissen, wie viel wir so verbrauchen.
- Strom
- Heizung
- Was vergessen?

**Comment by derphjl** [comment]
Der Stromzähler ist in einem großen Zählerraum, den man nur über die Hausverwaltung erreicht. Hier müssen wir mal Günther fragen, wie man da genau ran kommt, wen man genau anrufen muss, etc.

**Comment by KingBBQ** [comment]
die alten Sachen müssen wir auch ablesen und ummelden. Können wir ja bei der Übergabe machen...

**Comment by KingBBQ** [comment]
abgelesen durch @derphjl - gerade beim anbieter online umgemeldet.
