### ISSUE TITLE
Luga Bescheid sagen

### ISSUE THREAD

**Issue by KingBBQ** [openlab-aux/orgafoo#302]

**Comment by KingBBQ** [comment]
- Schrank Vorstand 
- neuer Raum

**Comment by KingBBQ** [comment]
mail geschickt an bekannten Kontakt.

**Comment by robinkaranu** [comment]
Sie kamen vorbei und haben uns den Schlüssel für ihre Schublade zum Transport des Schranks in den Keller da gelassen. Außerdem wurden ein paar Fotos für die LUGA-Members gemacht. Die LUGA-Treffen sind noch virtuell.
