### ISSUE TITLE
3D-Drucker im Schaufenster aufbauen

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#303]

**Comment by robinkaranu** [comment]
Das 3D-Druck-Rack steht vorbereitet für's verschrauben im Saal. Das OpenLab sucht die Tüte mit den Schrauben!

**Comment by derphjl** [comment]
Der Dienstag, 26.4. bietet sich wunderbar an, um das Regal aufzubauen. Da ist nämlich eh der 3D-Drucker-Abend.

**Comment by derphjl** [comment]
Die Drucker haben den Drucker errichtet. Man kann ihm schön durchs Schufenster zuschauen.
