### ISSUE TITLE
Alte Spülmaschine verscherbeln, neue besorgen, anschließen.

### ISSUE THREAD

**Issue by derphjl** [openlab-aux/orgafoo#306]
Die alte Spülmaschine ist in die Jahre gekommen und, weil unterbaumodell, für den neuen Space nicht geeignet.

**Comment by derphjl** [comment]
Neue Spülmaschine ist organisiert, angeschlossen, läuft. Die alte Spülmaschine muss noch aus dem alten Lab geschafft werden. Verkaufen? Verschenken? Entsorgen? Vielleicht wollen sie die nachmieter? Kann ich mir ja schlecht vorstellen.

**Comment by robinkaranu** [comment]
Die Alte Spülmaschine wurde heute entsorgt.
