### ISSUE TITLE
Ankauf Fräsmaschine von Renes Boss

### ISSUE THREAD

**Issue by Joeend** [openlab-aux/orgafoo#309]
Crowd-Funding Ziel: 1000 €:
Jörg 100 €

100 von Jörg und 100 von aleonath an blechtaler am 16.6. übergeben

**Comment by Profpatsch** [comment]
Würde 100€ beisteuern.

**Comment by robinkaranu** [comment]
100 + 100 + 30: 230 von 1000

**Comment by Aelonath** [comment]
100 €

**Comment by momo-aux** [comment]
+100€

**Comment by craftamap** [comment]
+35

**Comment by paulalilulelo** [comment]
+50 (auch nochmal hier)

**Comment by robinkaranu** [comment]
Das Ding steht bei uns und eine Hand voll Menschis arbeiten schon daran, sie in Betrieb zu nehmen.
