### ISSUE TITLE
Brandmelder in Betrieb nehmen

### ISSUE THREAD

**Issue by robinkaranu** [openlab-aux/orgafoo#311]
Wir müssen Rauch-/Brandmelder besorgen und montieren. Es gab den Wunsch, vernetzte Melder zu besorgen, aber was? Hat zufällig schonmal jemand recherchiert oder Erfahrungen?

Ansonsten würde ich kurzfristig eher einfache besorgen, die erfüllen ihren Zweck auch besser als keine.

**Comment by robinkaranu** [comment]
Ich setze mir eine Deadline, bis zum Sonntag rauchmelder online bestellt zu haben.

**Comment by robinkaranu** [comment]
Sie sind inzwischen bestellt und kommen vermutlich am Montag an.

**Comment by derphjl** [comment]
@robinkaranu hat die Melder bestellt und sie kamen an, wir haben sie zusammen noch am selben Abend montiert. Aus dem Satz vernetzter Rauchmelder (photoelektrisch), es sind insgesamt 6 stück, hängen nun welche an folgenden Stellen:

- Im Lagerkeller in der Nähe der Tür
- Im Kellerflur vor dem Bad mit Dusche und Klo
- Im Treppenhaus, oberhalb der Lampe
- Im Hauptraum, in der Raummitte
- Im Sofazimmer, in der Raummitte
- Im Flur, etwa vor dem E-Labor

Dieser Reihe nach haben wir sie auch miteinander gepaired. Niemand weiß, ob dieses spezifische Modell jetzt Mesh, Broadcast, wasauchimmer macht. Aber in jedem Fall sind sie jetzt gut montiert :)
