### ISSUE TITLE
Mattermost Bestätigungsmail kommt nicht an

### ISSUE THREAD

**Issue by Mawarii** [openlab-aux/orgafoo#315]
Hey, 

hab auf die Schnelle keinen anderen Weg gefunden euch bescheid zu geben, aber die Mattermost Bestätigungsmail kam nie bei mir an. Ist jetzt paar Wochen her und habs zwischendurch immer wieder mal probiert. Hab auch 20x überprüft, ob ich mich nicht vlt vertippt habe (hab ich nicht) und andere Mails kommen auch an.
Ich wollte diesen Donnerstag eh mal vorbeischnein, aber ich vergess das mit der Mail bis dahin vmtl, deshalb hier das Issue.

**Comment by robinkaranu** [comment]
Hey danke - @muesli das ist dein Mailserver, oder? Kannst du mal ins Log gucken, was schief geht?

**Comment by muesli** [comment]
An welche Domain ging denn die Mail?

**Comment by Mawarii** [comment]
s-kapi.com

**Comment by muesli** [comment]
```
mail.info:Apr 22 15:04:49 mail postfix/smtp[2228153]: DB8CABDC1DB3: to=<mawari@s-kapi.com>, relay=mx01.kundenserver.de[217.72.192.67]:25, delay=349215, delays=349215/0.02/0.19/0, dsn=4.0.0, status=deferred (host mx01.kundenserver.de[217.72.192.67] refused to talk to me: 554-kundenserver.de (mxeue110) Nemesis ESMTP Service not available 554-No SMTP service 554-Bad DNS PTR resource record.
```

Deine im DNS für die Domain hinterlegten Mailserver scheinen sich nicht für die Domain verantwortlich zu fühlen.

**Comment by muesli** [comment]
Oder er blockt bewusst meinen Server? Keine Ahnung was sich dein Provider für Mail-Spielregeln ausdenkt.

**Comment by Mawarii** [comment]
Hmm. Ok weird. Egal nicht so schlimm. Ich versuch ne andere Mail

**Comment by Mawarii** [comment]
Ja ich hab auch keine Ahnung. Gehört zu 1und1, ist jetzt also nicht so verwunderlich...

**Comment by Mawarii** [comment]
OK hat mit ner anderen Mail funktioniert. Danke dir!
