### ISSUE TITLE
5.1-Anlage mit rantanplan 5.1-mässig koppeln

### ISSUE THREAD

**Issue by moba** [openlab-aux/orgafoo#68]
Ich habe damals™ 6x-Klinke-zu-Klinke-Verlängerungen gekauft, damit wir rantanplan mit Surround verbinden können. Wäre schön, wenn das mal jemand™ in Angriff nehmen würde der da grad Elan verspürt die Kabel ausfindig zu machen und zu verlegen.

**Comment by moba** [comment]
Zusätzlich sollte man die Anlage nun im neuen Lab mal installieren, dh. Boxen platzieren, Kabel ziehen, Rantanplan wieder dranhängen. Dazu brauchen wir denke ich mehr Audiokabel.

**Comment by Profpatsch** [comment]
Siehe #148 Ende.

**Comment by sternenseemann** [comment]
Nicht mehr relevant.
