### ISSUE TITLE
Bibliothek einrichten

### ISSUE THREAD

**Issue by Profpatsch** [openlab-aux/orgafoo#73]
Momentan haben wir eine Büchersammlung.

Was benötigt wird:

* Minimum
  * Einen Verantwortlichen
  * Jedes Buch braucht einen Besitzer, im oder am Einband
  * Nach Kategorie sortiert
  * Aussortierstrategie bei zu wenig Platz
  * Verleihliste
* Nice to have
  * Liste der Bücher online (filterbar, über die Space-API)
  * …

**Comment by moba** [comment]
Vorerst https://www.openlab-augsburg.de/bibliothek/ + librarything
