### ISSUE TITLE
Sinnvolle Wand- / Deckenhalterung für Beamer

### ISSUE THREAD

**Issue by glaxx** [openlab-aux/orgafoo#97]
@moba hat vor einiger Zeit angeboten, dass er neuen Beamer beschafft. Vorraussetzung wäre allerdings eine passable Wandhalterung. Diese sollte folgende Eigenschaften aufweisen:

* drehbar
* höhenverstellbar

Bitte erkundigt euch bei eurem präferierten Händler nach passenden Angeboten und reicht sie weiter.

**Comment by moba** [comment]
Flypps hat 2 Deckenhalterungen besorgt. Beamer oder Geldquelle für Beamer fehlt. Ich mach das mal zu
